/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Czech
export default {
  'fabric.elements.share.form.title': 'Sdílet',
  'fabric.elements.share.form.send': 'Odeslat',
  'fabric.elements.share.form.retry': 'Zkusit znovu',
  'fabric.elements.share.form.comment.placeholder': 'Přidat zprávu',
  'fabric.elements.share.form.user-picker.placeholder':
    'Zadejte jméno, tým nebo e-mail',
  'fabric.elements.share.form.user-picker.add-more': 'Zadejte více',
  'fabric.elements.share.form.user-picker.validation.required':
    'Vyberte aspoň jednoho uživatele, tým nebo e-mail.',
  'fabric.elements.share.form.user-picker.no-options.emptyQuery':
    'Nepodařilo se najít žádné výsledky. Pozvěte lidi pomocí jejich e-mailové adresy.',
  'fabric.elements.share.form.user-picker.no-options':
    'Pro „{inputValue}“ se nepodařilo najít žádné výsledky. Pozvěte lidi pomocí jejich e-mailové adresy.',
  'fabric.elements.share.trigger.button.text': 'Sdílet',
  'fabric.elements.share.copylink.button.text': 'Zkopírovat odkaz',
  'fabric.elements.share.copied.to.clipboard.message':
    'Odkaz zkopírován do schránky',
  'fabric.elements.share.form.capabilities.info.message':
    'Svou pozvánku musíte poslat administrátorovi ke schválení',
  'fabric.elements.share.failure.message': 'Nelze sdílet',
};
