/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Czech
export default {
  'fabric.elements.share.form.title': 'Sdílet',
  'fabric.elements.share.form.send': 'Odeslat',
  'fabric.elements.share.form.retry': 'Zkusit znovu',
  'fabric.elements.share.form.comment.placeholder': 'Přidat zprávu',
  'fabric.elements.share.form.user-picker.placeholder.generic':
    'Zadejte jméno, tým nebo e-mail',
  'fabric.elements.share.form.user-picker.placeholder.existingUserOnly':
    'Zadejte jméno nebo tým',
  'fabric.elements.share.form.user-picker.add-more': 'Zadejte více',
  'fabric.elements.share.form.user-picker.validation.required':
    'Vyberte aspoň jednoho uživatele, tým nebo e-mail.',
  'fabric.elements.share.form.user-picker.no-options.domainBasedUserOnly':
    'Můžete pozvat pouze lidi s e-mailem v doméně {domains}. Chcete-li pozvat jiné lidi, obraťte se na svého administrátora.',
  'fabric.elements.share.form.user-picker.no-options.existingUserOnly':
    'Pro „{inputValue}“ se nepodařilo najít žádné výsledky.',
  'fabric.elements.share.form.user-picker.no-options.generic':
    'Pro „{inputValue}“ se nepodařilo najít žádné výsledky. Pozvěte lidi pomocí jejich e-mailové adresy.',
  'fabric.elements.share.trigger.button.icon.label': 'Ikona sdílení',
  'fabric.elements.share.trigger.button.text': 'Sdílet',
  'fabric.elements.share.trigger.button.tooltip.text': 'Sdílet',
  'fabric.elements.share.trigger.button.invite.text': 'Pozvat',
  'fabric.elements.share.copylink.button.icon.label':
    'Ikona zkopírování propojení',
  'fabric.elements.share.copylink.button.text': 'Zkopírovat odkaz',
  'fabric.elements.share.copied.to.clipboard.icon.label':
    'Ikona úspěšného zkopírování propojení',
  'fabric.elements.share.copied.to.clipboard.message':
    'Odkaz zkopírován do schránky',
  'fabric.elements.share.form.capabilities.info.message':
    'Svou pozvánku musíte poslat administrátorovi ke schválení',
  'fabric.elements.share.failure.icon.label': 'Ikona chyby',
  'fabric.elements.share.failure.message': 'Nelze sdílet',
  'fabric.elements.share.success.message':
    '{object, select, blogpost {Blog post shared} board {Board shared} kalendář {Calendar shared} koncept{Draft shared} filtr {Filter shared} požadavek {Issue shared} média {Media shared} stránka {Page shared} projekt {Project shared} pull request {Pull Request shared} otázka {Question shared} hlášení {Report shared} repozitář {Repository shared} žádost {Request shared} plán {Roadmap shared} web {Site shared} prostor {Space shared} další {Link Shared}}',
  'fabric.elements.share.admin.notified.message':
    'Váš administrátor byl upozorněn',
};
