/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Danish
export default {
  'fabric.elements.share.form.title': 'Del',
  'fabric.elements.share.form.send': 'Send',
  'fabric.elements.share.form.retry': 'Prøv igen',
  'fabric.elements.share.form.comment.placeholder': 'TIlføj en meddelelse',
  'fabric.elements.share.form.user-picker.placeholder':
    'Indtast navn, team eller e-mail',
  'fabric.elements.share.form.user-picker.add-more': 'Indtast mere',
  'fabric.elements.share.form.user-picker.validation.required':
    'Vælg mindst én bruger, ét team eller én e-mail.',
  'fabric.elements.share.form.user-picker.no-options.emptyQuery':
    'Vi kunne ikke finde nogen resultater. Invitér personer via en e-mailadresse.',
  'fabric.elements.share.form.user-picker.no-options':
    'Vi kunne ikke finde nogen resultater for "{inputValue}". Invitér personer via en e-mailadresse.',
  'fabric.elements.share.trigger.button.text': 'Del',
  'fabric.elements.share.copylink.button.text': 'Kopier link',
  'fabric.elements.share.copied.to.clipboard.message':
    'Link er kopieret til udklipsholder',
  'fabric.elements.share.form.capabilities.info.message':
    'Din invitation sendes til godkendelse hos en administrator',
  'fabric.elements.share.failure.message': 'Kan ikke deles',
};
