/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// German
export default {
  'fabric.elements.share.form.title': 'Teilen',
  'fabric.elements.share.form.send': 'Senden',
  'fabric.elements.share.form.retry': 'Erneut versuchen',
  'fabric.elements.share.form.comment.placeholder': 'Nachricht hinzufügen',
  'fabric.elements.share.form.user-picker.placeholder':
    'Namen, Team oder E-Mail-Adresse eingeben',
  'fabric.elements.share.form.user-picker.add-more': 'Weitere eingeben',
  'fabric.elements.share.form.user-picker.validation.required':
    'Wählen Sie mindestens einen Benutzer, ein Team oder eine E-Mail-Adresse aus.',
  'fabric.elements.share.form.user-picker.no-options.emptyQuery':
    'Es wurden keine Ergebnisse gefunden. Laden Sie Personen mittels E-Mail-Adresse ein.',
  'fabric.elements.share.form.user-picker.no-options':
    'Es wurden kein Ergebnisse für „{inputValue}“ gefunden. Laden Sie Personen mittels E-Mail-Adresse ein.',
  'fabric.elements.share.trigger.button.text': 'Teilen',
  'fabric.elements.share.copylink.button.text': 'Link kopieren',
  'fabric.elements.share.copied.to.clipboard.message':
    'Link in Zwischenablage kopiert',
  'fabric.elements.share.form.capabilities.info.message':
    'Ihre Einladung wird zur Genehmigung an einen Administrator gesendet.',
  'fabric.elements.share.failure.message': 'Teilen nicht möglich',
};
