/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// German
export default {
  'fabric.elements.share.form.title': 'Teilen',
  'fabric.elements.share.form.send': 'Senden',
  'fabric.elements.share.form.retry': 'Erneut versuchen',
  'fabric.elements.share.form.comment.placeholder': 'Nachricht hinzufügen',
  'fabric.elements.share.form.user-picker.placeholder.generic':
    'Namen, Team oder E-Mail-Adresse eingeben',
  'fabric.elements.share.form.user-picker.placeholder.existingUserOnly':
    'Namen oder Team eingeben',
  'fabric.elements.share.form.user-picker.add-more': 'Weitere eingeben',
  'fabric.elements.share.form.user-picker.validation.required':
    'Wählen Sie mindestens einen Benutzer, ein Team oder eine E-Mail-Adresse aus.',
  'fabric.elements.share.form.user-picker.no-options.domainBasedUserOnly':
    'Sie können nur Personen mit {domains}-E-Mail-Adressen einladen. Kontaktieren Sie Ihren Website-Administrator, um andere Personen einzuladen.',
  'fabric.elements.share.form.user-picker.no-options.existingUserOnly':
    'Es wurden kein Ergebnisse für "{inputValue}" gefunden.',
  'fabric.elements.share.form.user-picker.no-options.generic':
    'Es wurden kein Ergebnisse für "{inputValue}" gefunden. Laden Sie Personen mittels E-Mail-Adresse ein.',
  'fabric.elements.share.trigger.button.icon.label': 'Teilen-Symbol',
  'fabric.elements.share.trigger.button.text': 'Teilen',
  'fabric.elements.share.trigger.button.tooltip.text': 'Teilen',
  'fabric.elements.share.trigger.button.invite.text': 'Einladen',
  'fabric.elements.share.copylink.button.icon.label':
    'Symbol für Link kopieren',
  'fabric.elements.share.copylink.button.text': 'Link kopieren',
  'fabric.elements.share.copied.to.clipboard.icon.label':
    'Symbol für Link kopieren erfolgreich',
  'fabric.elements.share.copied.to.clipboard.message':
    'Link in Zwischenablage kopiert',
  'fabric.elements.share.form.capabilities.info.message':
    'Ihre Einladung wird zur Genehmigung an einen Administrator gesendet.',
  'fabric.elements.share.failure.icon.label': 'Fehler-Symbol',
  'fabric.elements.share.failure.message': 'Teilen nicht möglich',
  'fabric.elements.share.success.message':
    '{object, select, blogpost {Blog-Beitrag geteilt} board {Board geteilt} calendar {Kalender geteilt} draft {Entwurf geteilt} filter {Filter geteilt} issue {Vorgang geteilt} media {Medien geteilt} page {Seite geteilt} project {Projekt geteilt} pullrequest {Pull-Anfrage geteilt} question {Frage geteilt} report {Bericht geteilt} repository {Repository geteilt} request {Anfrage geteilt} roadmap {Roadmap geteilt} site {Site geteilt} space {Bereich geteilt} other {Link geteilt}}',
  'fabric.elements.share.admin.notified.message':
    'Ihr Admin wurde benachrichtigt.',
};
