/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// English
export default {
  'fabric.elements.share.form.title': 'Share',
  'fabric.elements.share.form.send': 'Send',
  'fabric.elements.share.form.retry': 'Retry',
  'fabric.elements.share.form.comment.placeholder': 'Add a message',
  'fabric.elements.share.form.user-picker.placeholder':
    'Enter name, team or email',
  'fabric.elements.share.form.user-picker.add-more': 'Enter more',
  'fabric.elements.share.form.user-picker.validation.required':
    'Select at least one user, team or email.',
  'fabric.elements.share.form.user-picker.no-options.emptyQuery':
    'We couldn’t find any results. Invite people by using an email address.',
  'fabric.elements.share.form.user-picker.no-options':
    'We couldn’t find any results for "{inputValue}". Invite people by using an email address.',
  'fabric.elements.share.trigger.button.text': 'Share',
  'fabric.elements.share.copylink.button.text': 'Copy link',
  'fabric.elements.share.copied.to.clipboard.message':
    'Link copied to clipboard',
  'fabric.elements.share.form.capabilities.info.message':
    'Your invite will be sent to an admin for approval',
  'fabric.elements.share.failure.message': 'Unable to share',
};
