/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Spanish
export default {
  'fabric.elements.share.form.title': 'Compartir',
  'fabric.elements.share.form.send': 'Enviar',
  'fabric.elements.share.form.retry': 'Reintentar',
  'fabric.elements.share.form.comment.placeholder': 'Añade un mensaje',
  'fabric.elements.share.form.user-picker.placeholder.generic':
    'Introduce un nombre, equipo o correo electrónico',
  'fabric.elements.share.form.user-picker.placeholder.existingUserOnly':
    'Introduce un nombre o equipo',
  'fabric.elements.share.form.user-picker.add-more': 'Introduce más cosas',
  'fabric.elements.share.form.user-picker.validation.required':
    'Selecciona al menos un usuario, equipo o correo electrónico.',
  'fabric.elements.share.form.user-picker.no-options.domainBasedUserOnly':
    'Solo puedes invitar a personas con direcciones de correo electrónico de {domains}. Ponte en contacto con el administrador del sitio para invitar a otras personas.',
  'fabric.elements.share.form.user-picker.no-options.existingUserOnly':
    'No hemos encontrado ningún resultado para "{inputValue}".',
  'fabric.elements.share.form.user-picker.no-options.generic':
    'No hemos encontrado ningún resultado para "{inputValue}". Invita a la gente mediante una dirección de correo electrónico.',
  'fabric.elements.share.trigger.button.icon.label': 'Compartir icono',
  'fabric.elements.share.trigger.button.text': 'Compartir',
  'fabric.elements.share.trigger.button.tooltip.text': 'Compartir',
  'fabric.elements.share.trigger.button.invite.text': 'Invitar',
  'fabric.elements.share.copylink.button.icon.label': 'Copiar icono de enlace',
  'fabric.elements.share.copylink.button.text': 'Copiar enlace',
  'fabric.elements.share.copied.to.clipboard.icon.label':
    'Copiar icono de enlace correcto',
  'fabric.elements.share.copied.to.clipboard.message':
    'Enlace copiado en el portapapeles',
  'fabric.elements.share.form.capabilities.info.message':
    'Se enviará tu invitación a un administrador para que la apruebe',
  'fabric.elements.share.failure.icon.label': 'Icono de error',
  'fabric.elements.share.failure.message': 'No se puede compartir',
  'fabric.elements.share.success.message':
    '{object, select, blogpost {Entrada de blog compartida} board {Tablero compartido} calendar {Calendario compartido} draft {Borrador compartido} filter {Filtro compartido} issue {Incidencia compartida} media {Medios compartidos} page {Página compartida} project {Proyecto compartido} pullrequest {Solicitud de incorporación de cambios compartida} question {Pregunta compartida} report {Informe compartido} repository {Repositorio compartido} request {Solicitud compartida} roadmap {Hoja de ruta compartida} site {Sitio compartido} space {Espacio compartido} other {Enlace compartido}}',
  'fabric.elements.share.admin.notified.message':
    'Se ha notificado a tu administrador',
};
