/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Spanish
export default {
  'fabric.elements.share.form.title': 'Compartir',
  'fabric.elements.share.form.send': 'Enviar',
  'fabric.elements.share.form.retry': 'Reintentar',
  'fabric.elements.share.form.comment.placeholder': 'Añade un mensaje',
  'fabric.elements.share.form.user-picker.placeholder':
    'Introduce un nombre, equipo o correo electrónico',
  'fabric.elements.share.form.user-picker.add-more': 'Introduce más cosas',
  'fabric.elements.share.form.user-picker.validation.required':
    'Selecciona al menos un usuario, equipo o correo electrónico.',
  'fabric.elements.share.form.user-picker.no-options.emptyQuery':
    'No hemos encontrado ningún resultado. Invita a la gente mediante una dirección de correo electrónico.',
  'fabric.elements.share.form.user-picker.no-options':
    'No hemos encontrado ningún resultado para "{inputValue}". Invita a la gente mediante una dirección de correo electrónico.',
  'fabric.elements.share.trigger.button.text': 'Compartir',
  'fabric.elements.share.copylink.button.text': 'Copiar enlace',
  'fabric.elements.share.copied.to.clipboard.message':
    'Enlace copiado en el portapapeles',
  'fabric.elements.share.form.capabilities.info.message':
    'Se enviará tu invitación a un administrador para que la apruebe',
  'fabric.elements.share.failure.message': 'No se puede compartir',
};
