/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Estonian
export default {
  'fabric.elements.share.form.title': 'Jaga',
  'fabric.elements.share.form.send': 'Saada',
  'fabric.elements.share.form.retry': 'Proovi uuesti',
  'fabric.elements.share.form.comment.placeholder': 'Sõnumi lisamine',
  'fabric.elements.share.form.user-picker.placeholder':
    'Sisesta nimi, meeskond või e-posti aadress',
  'fabric.elements.share.form.user-picker.add-more': 'Sisesta veel',
  'fabric.elements.share.form.user-picker.validation.required':
    'Vali vähemalt üks kasutaja, meeskond või e-posti aadress.',
  'fabric.elements.share.form.user-picker.no-options.emptyQuery':
    'Me ei suutnud leida ühtegi tulemust. Kutsu inimesi e-posti aadressi alusel.',
  'fabric.elements.share.form.user-picker.no-options':
    'Me ei suutnud leida ühtegi tulemust seoses otsitavaga „{inputValue}". Kutsu inimesi e-posti aadressi alusel.',
  'fabric.elements.share.trigger.button.text': 'Jaga',
  'fabric.elements.share.copylink.button.text': 'Kopeeri link',
  'fabric.elements.share.copied.to.clipboard.message':
    'Link kopeeritud lõikelauale',
  'fabric.elements.share.form.capabilities.info.message':
    'Kutse saadetakse administraatorile heaks kiitmiseks',
  'fabric.elements.share.failure.message': 'Jagamine nurjus',
};
