/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Estonian
export default {
  'fabric.elements.share.form.title': 'Jaga',
  'fabric.elements.share.form.send': 'Saada',
  'fabric.elements.share.form.retry': 'Proovi uuesti',
  'fabric.elements.share.form.comment.placeholder': 'Sõnumi lisamine',
  'fabric.elements.share.form.user-picker.placeholder.generic':
    'Sisesta nimi, meeskond või e-posti aadress',
  'fabric.elements.share.form.user-picker.placeholder.existingUserOnly':
    'Sisesta nimi või meeskond',
  'fabric.elements.share.form.user-picker.add-more': 'Sisesta veel',
  'fabric.elements.share.form.user-picker.validation.required':
    'Vali vähemalt üks kasutaja, meeskond või e-posti aadress.',
  'fabric.elements.share.form.user-picker.no-options.domainBasedUserOnly':
    'Saad kutsuda vaid {domains} e-posti aadressiga inimesi. Teiste kutsumiseks võta ühendust lehe administraatoriga.',
  'fabric.elements.share.form.user-picker.no-options.existingUserOnly':
    'Me ei suutnud leida ühtegi tulemust seoses otsitavaga „{inputValue}". ',
  'fabric.elements.share.form.user-picker.no-options.generic':
    'Me ei suutnud leida ühtegi tulemust seoses otsitavaga „{inputValue}". Kutsu inimesi e-posti aadressi alusel.',
  'fabric.elements.share.trigger.button.icon.label': 'Jagamisikoon',
  'fabric.elements.share.trigger.button.text': 'Jaga',
  'fabric.elements.share.trigger.button.tooltip.text': 'Jaga',
  'fabric.elements.share.trigger.button.invite.text': 'Kutsu',
  'fabric.elements.share.copylink.button.icon.label': 'Kopeeri lingi ikoon',
  'fabric.elements.share.copylink.button.text': 'Kopeeri link',
  'fabric.elements.share.copied.to.clipboard.icon.label':
    'Lingi eduka kopeerimise ikoon',
  'fabric.elements.share.copied.to.clipboard.message':
    'Link kopeeritud lõikelauale',
  'fabric.elements.share.form.capabilities.info.message':
    'Kutse saadetakse administraatorile heaks kiitmiseks',
  'fabric.elements.share.failure.icon.label': 'Vea ikoon',
  'fabric.elements.share.failure.message': 'Jagamine nurjus',
  'fabric.elements.share.success.message':
    '{object, select, blogpost {Blog post shared} tahvel {Board shared} kalender {Calendar shared} mustand {Draft shared} filter {Filter shared} probleem {Issue shared} meedia {Media shared} lehekülg {Page shared} projekt {Project shared} tõmbekutse {Pull Request shared} küsimus {Question shared} aruanne {Report shared}koodihoidla  {Repository shared} taotlus {Request shared}tööplaan  {Roadmap shared} leht {Site shared} ruum {Space shared} muu {Link Shared}}',
  'fabric.elements.share.admin.notified.message':
    'Sinu administraatorit on teavitatud',
};
