/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Finnish
export default {
  'fabric.elements.share.form.title': 'Jaa',
  'fabric.elements.share.form.send': 'Lähetä',
  'fabric.elements.share.form.retry': 'Yritä uudelleen',
  'fabric.elements.share.form.comment.placeholder': 'Lisää viesti',
  'fabric.elements.share.form.user-picker.placeholder':
    'Anna nimi, tiimi tai sähköpostiosoite',
  'fabric.elements.share.form.user-picker.add-more': 'Syötä lisää',
  'fabric.elements.share.form.user-picker.validation.required':
    'Valitse vähintään yksi käyttäjä, tiimi tai sähköpostiosoite.',
  'fabric.elements.share.form.user-picker.no-options.emptyQuery':
    'Tuloksia ei löytynyt. Kutsu henkilöitä sähköpostiosoitteen avulla.',
  'fabric.elements.share.form.user-picker.no-options':
    'Tuloksia ei löytynyt haulle "{inputValue}". Kutsu henkilöitä sähköpostiosoitteen avulla.',
  'fabric.elements.share.trigger.button.text': 'Jaa',
  'fabric.elements.share.copylink.button.text': 'Kopioi linkki',
  'fabric.elements.share.copied.to.clipboard.message':
    'Linkki kopioitu leikepöydälle',
  'fabric.elements.share.form.capabilities.info.message':
    'Kutsusi lähetetään ylläpitäjälle hyväksyttäväksi',
  'fabric.elements.share.failure.message': 'Ei voitu jakaa',
};
