/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// French
export default {
  'fabric.elements.share.form.title': 'Partager',
  'fabric.elements.share.form.send': 'Envoyer',
  'fabric.elements.share.form.retry': 'Réessayer',
  'fabric.elements.share.form.comment.placeholder': 'Ajouter un message',
  'fabric.elements.share.form.user-picker.placeholder':
    'Saisissez un nom, une équipe ou une adresse e-mail.',
  'fabric.elements.share.form.user-picker.add-more': 'Saisir plus d’éléments',
  'fabric.elements.share.form.user-picker.validation.required':
    'Sélectionnez au moins un utilisateur, une équipe ou une adresse e-mail.',
  'fabric.elements.share.form.user-picker.no-options.emptyQuery':
    "Pas de résultats. Invitez des personnes à l'aide d'une adresse e-mail.",
  'fabric.elements.share.form.user-picker.no-options':
    "Pas de résultats pour « {inputValue} ». Invitez des personnes à l'aide d'une adresse e-mail.",
  'fabric.elements.share.trigger.button.text': 'Partager',
  'fabric.elements.share.copylink.button.text': 'Copier le lien',
  'fabric.elements.share.copied.to.clipboard.message':
    'Lien copié dans le presse-papier',
  'fabric.elements.share.form.capabilities.info.message':
    'Votre invitation sera envoyée à un administrateur pour approbation',
  'fabric.elements.share.failure.message': 'Partage impossible',
};
