/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Hungarian
export default {
  'fabric.elements.share.form.title': 'Megosztás',
  'fabric.elements.share.form.send': 'Küldés',
  'fabric.elements.share.form.retry': 'Újra',
  'fabric.elements.share.form.comment.placeholder': 'Üzenet hozzáadása',
  'fabric.elements.share.form.user-picker.placeholder':
    'Adja meg a nevet, csapatot vagy e-mail-címet',
  'fabric.elements.share.form.user-picker.add-more': 'Továbbiak megadása',
  'fabric.elements.share.form.user-picker.validation.required':
    'Válasszon ki legalább egy felhasználót, csapatot vagy e-mail-címet.',
  'fabric.elements.share.form.user-picker.no-options.emptyQuery':
    'Nincs találat. Próbáld meg módosítani a keresési feltételeket.',
  'fabric.elements.share.form.user-picker.no-options':
    'Nincs találat a következő keresésre: „{inputValue}”. Hívj meg embereket az e-mail-címük alapján.',
  'fabric.elements.share.trigger.button.text': 'Megosztás',
  'fabric.elements.share.copylink.button.text': 'Hivatkozás másolása',
  'fabric.elements.share.copied.to.clipboard.message':
    'Hivatkozás átmásolva a vágólapra',
  'fabric.elements.share.form.capabilities.info.message':
    'A meghívóját a rendszer elküldi egy adminisztrátornak jóváhagyásra',
  'fabric.elements.share.failure.message': 'Nem lehet megosztani',
};
