/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Icelandic
export default {
  'fabric.elements.share.form.title': 'Deila',
  'fabric.elements.share.form.send': 'Senda ',
  'fabric.elements.share.form.retry': 'Reyna aftur',
  'fabric.elements.share.form.comment.placeholder': 'Bæta við skilaboðum',
  'fabric.elements.share.form.user-picker.placeholder':
    'Sláðu inn nafn, teymi eða tölvupóstur',
  'fabric.elements.share.form.user-picker.add-more': 'Færa inn fleiri ',
  'fabric.elements.share.form.user-picker.validation.required':
    'Veldu að minnsta kosti einn notanda, teymi eða netfang.',
  'fabric.elements.share.form.user-picker.no-options.emptyQuery':
    'Ekki fundust neinar niðurstöður. Bjóddu fólki með því að nota netföng.',
  'fabric.elements.share.form.user-picker.no-options':
    'Ekki fundust neinar niðurstöður fyrir "{inputValue}". Bjóddu fólki með því að nota netföng.',
  'fabric.elements.share.trigger.button.text': 'Deila',
  'fabric.elements.share.copylink.button.text': 'Afrita tengil',
  'fabric.elements.share.copied.to.clipboard.message':
    'Tengill afritaður á klippiborð',
  'fabric.elements.share.form.capabilities.info.message':
    'Boðskortið þitt verður sent til stjórnanda til samþykkis',
  'fabric.elements.share.failure.message': 'Ekki er hægt að deila',
};
