/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Italian
export default {
  'fabric.elements.share.form.title': 'Condividi',
  'fabric.elements.share.form.send': 'Invia',
  'fabric.elements.share.form.retry': 'Riprova',
  'fabric.elements.share.form.comment.placeholder': 'Aggiungi un messaggio',
  'fabric.elements.share.form.user-picker.placeholder':
    'Inserisci nome, team o e-mail',
  'fabric.elements.share.form.user-picker.add-more': 'Inerisci altri elementi',
  'fabric.elements.share.form.user-picker.validation.required':
    'Seleziona almeno un utente, un team o un’e-mail.',
  'fabric.elements.share.form.user-picker.no-options.emptyQuery':
    'Non è stato possibile trovare alcun risultato. Invita le persone utilizzando un indirizzo e-mail.',
  'fabric.elements.share.form.user-picker.no-options':
    'Non è stato possibile trovare risultati per "{inputValue}". Invita le persone utilizzando un indirizzo e-mail.',
  'fabric.elements.share.trigger.button.text': 'Condividi',
  'fabric.elements.share.copylink.button.text': 'Copia link',
  'fabric.elements.share.copied.to.clipboard.message':
    'Link copiato negli appunti',
  'fabric.elements.share.form.capabilities.info.message':
    'Il tuo invito verrà mandato a un amministratore per l’approvazione',
  'fabric.elements.share.failure.message':
    'Impossibile effettuare la condivisione',
};
