/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Japanese
export default {
  'fabric.elements.share.form.title': 'シェア',
  'fabric.elements.share.form.send': '送信',
  'fabric.elements.share.form.retry': '再試行',
  'fabric.elements.share.form.comment.placeholder': 'メッセージを追加',
  'fabric.elements.share.form.user-picker.placeholder.generic':
    '名前、チーム、または E メールを入力',
  'fabric.elements.share.form.user-picker.placeholder.existingUserOnly':
    '名前またはチームを入力',
  'fabric.elements.share.form.user-picker.add-more': 'さらに追加',
  'fabric.elements.share.form.user-picker.validation.required':
    '少なくともユーザー、チームまたはメールを 1 つ選択してください。',
  'fabric.elements.share.form.user-picker.no-options.domainBasedUserOnly':
    '{domains} のメール アドレスを使用しているユーザーのみを招待できます。その他のユーザーを招待するには、サイト管理者にお問い合わせください。',
  'fabric.elements.share.form.user-picker.no-options.existingUserOnly':
    '"{inputValue}" に一致する結果が見つかりませんでした。',
  'fabric.elements.share.form.user-picker.no-options.generic':
    '"{inputValue}" に一致する結果が見つかりませんでした。メール アドレスを使用してユーザーを招待してください。',
  'fabric.elements.share.trigger.button.icon.label': '共有アイコン',
  'fabric.elements.share.trigger.button.text': 'シェア',
  'fabric.elements.share.trigger.button.tooltip.text': '共有',
  'fabric.elements.share.trigger.button.invite.text': '招待',
  'fabric.elements.share.copylink.button.icon.label': 'リンクをコピー アイコン',
  'fabric.elements.share.copylink.button.text': 'リンクをコピー',
  'fabric.elements.share.copied.to.clipboard.icon.label':
    'リンクのコピー成功アイコン',
  'fabric.elements.share.copied.to.clipboard.message':
    'リンクをクリップボードにコピーしました',
  'fabric.elements.share.form.capabilities.info.message':
    '招待は、承認のため管理者に送信されます',
  'fabric.elements.share.failure.icon.label': 'エラー アイコン',
  'fabric.elements.share.failure.message': 'シェアできません',
  'fabric.elements.share.success.message':
    '{object, select, blogpost {Blog post shared} ボード {Board shared} カレンダー {Calendar shared} 下書き {Draft shared} フィルター {Filter shared} 課題 {Issue shared} メディア {Media shared} ページ {Page shared} プロジェクト {Project shared} プル リクエスト {Pull Request shared} 質問 {Question shared} レポート {Report shared} リポジトリ {Repository shared} リクエスト {Request shared} ロードマップ {Roadmap shared} サイト {Site shared} スペース {Space shared} その他 {Link Shared}}',
  'fabric.elements.share.admin.notified.message':
    '管理者に通知が送信されました',
};
