/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Japanese
export default {
  'fabric.elements.share.form.title': 'シェア',
  'fabric.elements.share.form.send': '送信',
  'fabric.elements.share.form.retry': '再試行',
  'fabric.elements.share.form.comment.placeholder': 'メッセージを追加',
  'fabric.elements.share.form.user-picker.placeholder':
    'ユーザー名、チーム、またはメールを入力',
  'fabric.elements.share.form.user-picker.add-more': 'さらに追加',
  'fabric.elements.share.form.user-picker.validation.required':
    '少なくともユーザー、チームまたはメールを 1 つ選択してください。',
  'fabric.elements.share.form.user-picker.no-options.emptyQuery':
    '一致する結果が見つかりませんでした。メールアドレスを使用してユーザーを招待してください。',
  'fabric.elements.share.form.user-picker.no-options':
    '"{inputValue}" に一致する結果が見つかりませんでした。メールアドレスを使用してユーザーを招待してください。',
  'fabric.elements.share.trigger.button.text': 'シェア',
  'fabric.elements.share.copylink.button.text': 'リンクをコピー',
  'fabric.elements.share.copied.to.clipboard.message':
    'リンクをクリップボードにコピーしました',
  'fabric.elements.share.form.capabilities.info.message':
    '招待は、承認のため管理者に送信されます',
  'fabric.elements.share.failure.message': 'シェアできません',
};
