/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Korean
export default {
  'fabric.elements.share.form.title': '공유',
  'fabric.elements.share.form.send': '전송',
  'fabric.elements.share.form.retry': '재시도',
  'fabric.elements.share.form.comment.placeholder': '메시지 추가',
  'fabric.elements.share.form.user-picker.placeholder.generic':
    '이름, 팀 또는 이메일 입력',
  'fabric.elements.share.form.user-picker.placeholder.existingUserOnly':
    '이름 또는 팀 입력',
  'fabric.elements.share.form.user-picker.add-more': '추가 입력',
  'fabric.elements.share.form.user-picker.validation.required':
    '사용자, 팀 또는 이메일을 최소한 하나 선택하십시오.',
  'fabric.elements.share.form.user-picker.no-options.domainBasedUserOnly':
    '{domains} 이메일 주소로만 사람들을 초대할 수 있습니다. 사이트 관리자에게 문의하여 다른 사람을 초대해보세요.',
  'fabric.elements.share.form.user-picker.no-options.existingUserOnly':
    '"{inputValue}"에 대한 결과를 찾지 못했습니다.',
  'fabric.elements.share.form.user-picker.no-options.generic':
    '"{inputValue}"에 대한 결과를 찾지 못했습니다. 이메일 주소를 사용하여 사람들을 초대해 보세요.',
  'fabric.elements.share.trigger.button.icon.label': '공유 아이콘',
  'fabric.elements.share.trigger.button.text': '공유',
  'fabric.elements.share.trigger.button.tooltip.text': '공유',
  'fabric.elements.share.trigger.button.invite.text': '초대',
  'fabric.elements.share.copylink.button.icon.label': '링크 복사 아이콘',
  'fabric.elements.share.copylink.button.text': '연결 복사',
  'fabric.elements.share.copied.to.clipboard.icon.label':
    '링크 복사 성공 아이콘',
  'fabric.elements.share.copied.to.clipboard.message':
    '연결이 클립보드에 복사됨',
  'fabric.elements.share.form.capabilities.info.message':
    '초대가 승인을 위해 관리자에게 전송되었습니다.',
  'fabric.elements.share.failure.icon.label': '오류 아이콘',
  'fabric.elements.share.failure.message': '공유할 수 없음',
  'fabric.elements.share.success.message':
    '{object, select, blogpost {Blog post shared} 보드 {Board shared} 캘린더 {Calendar shared} 임시본 {Draft shared} 필터 {Filter shared} 이슈 {Issue shared} 미디어 {Media shared} 페이지 {Page shared} 프로젝트 {Project shared} 풀 리퀘스트 {Pull Request shared} 질문 {Question shared} 보고서 {Report shared} 리포지토리 {Repository shared} 리퀘스트 {Request shared} 로드맵 {Roadmap shared} 사이트 {Site shared} 스페이스 {Space shared} 기타 {Link Shared}}',
  'fabric.elements.share.admin.notified.message': '관리자에게 전달했습니다.',
};
