/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Korean
export default {
  'fabric.elements.share.form.title': '공유',
  'fabric.elements.share.form.send': '전송',
  'fabric.elements.share.form.retry': '재시도',
  'fabric.elements.share.form.comment.placeholder': '메시지 추가',
  'fabric.elements.share.form.user-picker.placeholder':
    '이름, 팀 또는 이메일 입력',
  'fabric.elements.share.form.user-picker.add-more': '추가 입력',
  'fabric.elements.share.form.user-picker.validation.required':
    '사용자, 팀 또는 이메일을 최소한 하나 선택하십시오.',
  'fabric.elements.share.form.user-picker.no-options.emptyQuery':
    '결과를 찾지 못했습니다. 이메일 주소를 사용하여 사람들을 초대해 보세요.',
  'fabric.elements.share.form.user-picker.no-options':
    '"{inputValue}"에 대한 결과를 찾지 못했습니다. 이메일 주소를 사용하여 사람들을 초대해 보세요.',
  'fabric.elements.share.trigger.button.text': '공유',
  'fabric.elements.share.copylink.button.text': '연결 복사',
  'fabric.elements.share.copied.to.clipboard.message':
    '연결이 클립보드에 복사됨',
  'fabric.elements.share.form.capabilities.info.message':
    '초대가 승인을 위해 관리자에게 전송되었습니다.',
  'fabric.elements.share.failure.message': '공유할 수 없음',
};
