/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Norwegian Bokmål
export default {
  'fabric.elements.share.form.title': 'Del',
  'fabric.elements.share.form.send': 'Send',
  'fabric.elements.share.form.retry': 'Prøv igjen',
  'fabric.elements.share.form.comment.placeholder': 'Legg til en melding',
  'fabric.elements.share.form.user-picker.placeholder':
    'Skriv inn navn, team eller e-post',
  'fabric.elements.share.form.user-picker.add-more': 'Legg til mer',
  'fabric.elements.share.form.user-picker.validation.required':
    'Velg minst én gruppe, et team eller en e-postadresse.',
  'fabric.elements.share.form.user-picker.no-options.emptyQuery':
    'Vi fant ingen resultater. Inviter folk ved å bruke en e-postadresse.',
  'fabric.elements.share.form.user-picker.no-options':
    'Vi fant ingen resultater for {inputValue}. Inviter folk ved å bruke en e-postadresse.',
  'fabric.elements.share.trigger.button.text': 'Del',
  'fabric.elements.share.copylink.button.text': 'Kopier kobling',
  'fabric.elements.share.copied.to.clipboard.message':
    'Kobling er kopiert til utklippstavlen',
  'fabric.elements.share.form.capabilities.info.message':
    'Invitasjonen vil bli sendt til en administrator for godkjenning',
  'fabric.elements.share.failure.message': 'Kan ikke deles',
};
