/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Norwegian Bokmål
export default {
  'fabric.elements.share.form.title': 'Del',
  'fabric.elements.share.form.send': 'Send',
  'fabric.elements.share.form.retry': 'Prøv igjen',
  'fabric.elements.share.form.comment.placeholder': 'Legg til en melding',
  'fabric.elements.share.form.user-picker.placeholder.generic':
    'Skriv inn navn, team eller e-post',
  'fabric.elements.share.form.user-picker.placeholder.existingUserOnly':
    'Skriv inn navn eller team',
  'fabric.elements.share.form.user-picker.add-more': 'Legg til mer',
  'fabric.elements.share.form.user-picker.validation.required':
    'Velg minst én gruppe, et team eller en e-postadresse.',
  'fabric.elements.share.form.user-picker.no-options.domainBasedUserOnly':
    'Du kan bare invitere folk med e-postadresser som tilhører {domains}. Ta kontakt med sideadministratoren for å invitere andre.',
  'fabric.elements.share.form.user-picker.no-options.existingUserOnly':
    'Vi kunne ikke finne noen resultater for "{inputValue}".',
  'fabric.elements.share.form.user-picker.no-options.generic':
    'Vi kunne ikke finne noen resultater for "{inputValue}". Inviter personer ved å bruke en e-postadresse.',
  'fabric.elements.share.trigger.button.icon.label': 'Dele-ikon',
  'fabric.elements.share.trigger.button.text': 'Del',
  'fabric.elements.share.trigger.button.tooltip.text': 'Del',
  'fabric.elements.share.trigger.button.invite.text': 'Inviter',
  'fabric.elements.share.copylink.button.icon.label': 'Kopier kobling-ikon',
  'fabric.elements.share.copylink.button.text': 'Kopier kobling',
  'fabric.elements.share.copied.to.clipboard.icon.label':
    'Kopiert kobling-ikon',
  'fabric.elements.share.copied.to.clipboard.message':
    'Kobling er kopiert til utklippstavlen',
  'fabric.elements.share.form.capabilities.info.message':
    'Invitasjonen vil bli sendt til en administrator for godkjenning',
  'fabric.elements.share.failure.icon.label': 'Feil-ikon',
  'fabric.elements.share.failure.message': 'Kan ikke deles',
  'fabric.elements.share.success.message':
    '{object, select, blogpost {Blog post shared} tavle {Board shared} kalender {Calendar shared} utkast {Draft shared} filter {Filter shared} sak {Issue shared} media {Media shared} side {Page shared} prosjekt {Project shared} pull-forespørsel {Pull Request shared} spørsmål {Question shared} rapport {Report shared} repositorium {Repository shared} forespørsel {Request shared} veikart {Roadmap shared} side {Site shared} område {Space shared} annet {Link Shared}}',
  'fabric.elements.share.admin.notified.message':
    'Administratoren din har blitt varslet',
};
