/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Dutch
export default {
  'fabric.elements.share.form.title': 'Delen',
  'fabric.elements.share.form.send': 'Verzenden',
  'fabric.elements.share.form.retry': 'Opnieuw proberen',
  'fabric.elements.share.form.comment.placeholder': 'Voeg een bericht toe',
  'fabric.elements.share.form.user-picker.placeholder':
    'Vul een naam, team of e-mailadres in',
  'fabric.elements.share.form.user-picker.add-more': 'Meer items invoeren',
  'fabric.elements.share.form.user-picker.validation.required':
    'Selecteer minimaal één gebruiker, team of e-mailadres.',
  'fabric.elements.share.form.user-picker.no-options.emptyQuery':
    'We konden geen resultaten vinden. Nodig mensen uit met behulp van een e-mailadres.',
  'fabric.elements.share.form.user-picker.no-options':
    'We konden geen resultaten vinden voor "{inputValue}". Nodig mensen uit met behulp van een e-mailadres.',
  'fabric.elements.share.trigger.button.text': 'Delen',
  'fabric.elements.share.copylink.button.text': 'Link kopiëren',
  'fabric.elements.share.copied.to.clipboard.message':
    'Link naar het klembord gekopieerd',
  'fabric.elements.share.form.capabilities.info.message':
    'Je uitnodiging wordt naar een beheerder gestuurd ter goedkeuring',
  'fabric.elements.share.failure.message': 'Kan niet delen',
};
