/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Polish
export default {
  'fabric.elements.share.form.title': 'Udostępnij',
  'fabric.elements.share.form.send': 'Wyślij',
  'fabric.elements.share.form.retry': 'Ponów',
  'fabric.elements.share.form.comment.placeholder': 'Dodaj wiadomość',
  'fabric.elements.share.form.user-picker.placeholder':
    'Wprowadź nazwę, zespół lub adres e-mail',
  'fabric.elements.share.form.user-picker.add-more': 'Wprowadź więcej',
  'fabric.elements.share.form.user-picker.validation.required':
    'Wybierz co najmniej jednego użytkownika, zespół lub adres e-mail.',
  'fabric.elements.share.form.user-picker.no-options.emptyQuery':
    'Nie udało się znaleźć żadnych wyników. Zaproś ludzi za pomocą e-maila.',
  'fabric.elements.share.form.user-picker.no-options':
    'Nie udało się znaleźć wyników dla „{inputValue}”. Zaproś ludzi, używając adresu e-mail.',
  'fabric.elements.share.trigger.button.text': 'Udostępnij',
  'fabric.elements.share.copylink.button.text': 'Kopiuj łącze',
  'fabric.elements.share.copied.to.clipboard.message':
    'Łącze skopiowano do schowka',
  'fabric.elements.share.form.capabilities.info.message':
    'Twoje zaproszenie zostanie wysłane do administratora w celu zatwierdzenia',
  'fabric.elements.share.failure.message': 'Nie można udostępnić',
};
