/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Polish
export default {
  'fabric.elements.share.form.title': 'Udostępnij',
  'fabric.elements.share.form.send': 'Wyślij',
  'fabric.elements.share.form.retry': 'Ponów',
  'fabric.elements.share.form.comment.placeholder': 'Dodaj wiadomość',
  'fabric.elements.share.form.user-picker.placeholder.generic':
    'Wprowadź nazwę, zespół lub adres e-mail',
  'fabric.elements.share.form.user-picker.placeholder.existingUserOnly':
    'Wprowadź nazwę lub zespół',
  'fabric.elements.share.form.user-picker.add-more': 'Wprowadź więcej',
  'fabric.elements.share.form.user-picker.validation.required':
    'Wybierz co najmniej jednego użytkownika, zespół lub adres e-mail.',
  'fabric.elements.share.form.user-picker.no-options.domainBasedUserOnly':
    'Możesz zapraszać tylko osoby z adresami e-mail z domeny {domains}. Skontaktuj się z administratorem witryny, aby zaprosić innych użytkowników.',
  'fabric.elements.share.form.user-picker.no-options.existingUserOnly':
    'Nie udało się znaleźć wyników dla zapytania „{inputValue}”.',
  'fabric.elements.share.form.user-picker.no-options.generic':
    'Nie udało się znaleźć wyników dla „{inputValue}”. Zaproś ludzi, używając adresu e-mail.',
  'fabric.elements.share.trigger.button.icon.label': 'Udostępnij ikonę',
  'fabric.elements.share.trigger.button.text': 'Udostępnij',
  'fabric.elements.share.trigger.button.tooltip.text': 'Udostępnij',
  'fabric.elements.share.trigger.button.invite.text': 'Zaproś',
  'fabric.elements.share.copylink.button.icon.label': 'Ikona kopiowania łącza',
  'fabric.elements.share.copylink.button.text': 'Kopiuj łącze',
  'fabric.elements.share.copied.to.clipboard.icon.label':
    'Ikona udanego kopiowania łącza',
  'fabric.elements.share.copied.to.clipboard.message':
    'Łącze skopiowano do schowka',
  'fabric.elements.share.form.capabilities.info.message':
    'Twoje zaproszenie zostanie wysłane do administratora w celu zatwierdzenia',
  'fabric.elements.share.failure.icon.label': 'Ikona błędu',
  'fabric.elements.share.failure.message': 'Nie można udostępnić',
  'fabric.elements.share.success.message':
    '{object, select, blogpost {Blog post shared} tablica {Board shared} kalendarz {Calendar shared} szkic {Draft shared} filtr {Filter shared} zgłoszenie {Issue shared} multimedia {Media shared} strona {Page shared} projekt {Project shared} pullrequest {Pull Request shared} pytanie {Question shared} raport {Report shared} repozytorium {Repository shared} żądanie {Request shared} harmonogram {Roadmap shared} witryna {Site shared} przestrzeń {Space shared} inne {Link Shared}}',
  'fabric.elements.share.admin.notified.message':
    'Twój administrator został powiadomiony',
};
