/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Portuguese (Brazil)
export default {
  'fabric.elements.share.form.title': 'Compartilhar',
  'fabric.elements.share.form.send': 'Enviar',
  'fabric.elements.share.form.retry': 'Tentar novamente',
  'fabric.elements.share.form.comment.placeholder': 'Adicione uma mensagem',
  'fabric.elements.share.form.user-picker.placeholder':
    'Insira um nome, equipe ou e-mail',
  'fabric.elements.share.form.user-picker.add-more': 'Insira mais itens',
  'fabric.elements.share.form.user-picker.validation.required':
    'Selecione pelo menos um usuário, equipe ou e-mail.',
  'fabric.elements.share.form.user-picker.no-options.emptyQuery':
    'Não encontramos nenhum resultado. Convide pessoas usando um endereço de e-mail.',
  'fabric.elements.share.form.user-picker.no-options':
    'Não encontramos nenhum resultado para "{inputValue}". Convide pessoas usando um endereço de e-mail.',
  'fabric.elements.share.trigger.button.text': 'Compartilhar',
  'fabric.elements.share.copylink.button.text': 'Copiar link',
  'fabric.elements.share.copied.to.clipboard.message':
    'Link copiado para a área de transferência',
  'fabric.elements.share.form.capabilities.info.message':
    'Seu convite será enviado para a aprovação de um administrador',
  'fabric.elements.share.failure.message': 'Não foi possível compartilhar',
};
