/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Portuguese (Portugal)
export default {
  'fabric.elements.share.form.title': 'Partilhar',
  'fabric.elements.share.form.send': 'Enviar',
  'fabric.elements.share.form.retry': 'Tentar novamente',
  'fabric.elements.share.form.comment.placeholder': 'Adicionar uma mensagem',
  'fabric.elements.share.form.user-picker.placeholder':
    'Introduza o nome, equipa ou e-mail',
  'fabric.elements.share.form.user-picker.add-more': 'Introduza mais',
  'fabric.elements.share.form.user-picker.validation.required':
    'Selecione pelo menos um utilizador, equipa ou e-mail.',
  'fabric.elements.share.form.user-picker.no-options.emptyQuery':
    'Não foi possível encontrar resultados. Convite pessoas adicionando um endereço de e-mail.',
  'fabric.elements.share.form.user-picker.no-options':
    'Não foi possível encontrar resultados para "{inputValue}". Convite pessoas adicionando um endereço de e-mail.',
  'fabric.elements.share.trigger.button.text': 'Partilhar',
  'fabric.elements.share.copylink.button.text': 'Copiar ligação',
  'fabric.elements.share.copied.to.clipboard.message':
    'Ligação copiada para a área de transferência',
  'fabric.elements.share.form.capabilities.info.message':
    'O seu convite será enviado a um administrador para aprovação',
  'fabric.elements.share.failure.message': 'Não é possível partilhar',
};
