/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Romanian
export default {
  'fabric.elements.share.form.title': 'Partajați',
  'fabric.elements.share.form.send': 'Trimiteți',
  'fabric.elements.share.form.retry': 'Reîncercați',
  'fabric.elements.share.form.comment.placeholder': 'Adăugați un mesaj',
  'fabric.elements.share.form.user-picker.placeholder':
    'Introduceți nume, echipă sau e-mail',
  'fabric.elements.share.form.user-picker.add-more': 'Introduceți mai multe',
  'fabric.elements.share.form.user-picker.validation.required':
    'Selectați cel puțin un utilizator, echipă sau e-mail.',
  'fabric.elements.share.form.user-picker.no-options.emptyQuery':
    'Nu am găsit niciun rezultat. Invitați persoane utilizând o adresă de e-mail.',
  'fabric.elements.share.form.user-picker.no-options':
    'Nu am găsit niciun rezultat pentru "{inputValue}". Invită persoane utilizând o adresă de e-mail.',
  'fabric.elements.share.trigger.button.text': 'Partajați',
  'fabric.elements.share.copylink.button.text': 'Copiați link',
  'fabric.elements.share.copied.to.clipboard.message':
    'Link copiat în clipboard',
  'fabric.elements.share.form.capabilities.info.message':
    'Invitația dvs. va fi transmisă unui administrator pentru aprobare',
  'fabric.elements.share.failure.message': 'Nu se poate partaja',
};
