/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Russian
export default {
  'fabric.elements.share.form.title': 'Общий доступ',
  'fabric.elements.share.form.send': 'Отправить',
  'fabric.elements.share.form.retry': 'Еще раз',
  'fabric.elements.share.form.comment.placeholder': 'Введите сообщение',
  'fabric.elements.share.form.user-picker.placeholder':
    'Укажите имя, команду или адрес эл. почты',
  'fabric.elements.share.form.user-picker.add-more': 'Добавляйте еще',
  'fabric.elements.share.form.user-picker.validation.required':
    'Выберите хотя бы одного пользователя, команду или адрес эл. почты.',
  'fabric.elements.share.form.user-picker.no-options.emptyQuery':
    'Мы никого не нашли. Пригласите пользователей по адресу электронной почты.',
  'fabric.elements.share.form.user-picker.no-options':
    'Мы никого не нашли по запросу «{inputValue}». Пригласите пользователей по адресу электронной почты.',
  'fabric.elements.share.trigger.button.text': 'Поделиться',
  'fabric.elements.share.copylink.button.text': 'Копировать ссылку',
  'fabric.elements.share.copied.to.clipboard.message':
    'Ссылка скопирована в буфер обмена',
  'fabric.elements.share.form.capabilities.info.message':
    'Приглашение будет отправлено на рассмотрение администратору',
  'fabric.elements.share.failure.message': 'Не удалось поделиться',
};
