/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Slovak
export default {
  'fabric.elements.share.form.title': 'Zdieľanie',
  'fabric.elements.share.form.send': 'Odoslať',
  'fabric.elements.share.form.retry': 'Opakovať',
  'fabric.elements.share.form.comment.placeholder': 'Pridať správu',
  'fabric.elements.share.form.user-picker.placeholder':
    'Zadajte meno, tím alebo e-mail',
  'fabric.elements.share.form.user-picker.add-more': 'Zadajte ďalšie položky',
  'fabric.elements.share.form.user-picker.validation.required':
    'Vyberte aspoň jedného používateľa, tím alebo e-mail.',
  'fabric.elements.share.form.user-picker.no-options.emptyQuery':
    'Nepodarilo sa nájsť žiadne výsledky. Pozvite ľudí pomocou e-mailovej adresy.',
  'fabric.elements.share.form.user-picker.no-options':
    'Nepodarilo sa nájsť žiadne výsledky pre „{inputValue}“. Pozvite ľudí pomocou e-mailovej adresy.',
  'fabric.elements.share.trigger.button.text': 'Zdieľať',
  'fabric.elements.share.copylink.button.text': 'Kopírovať prepojenie',
  'fabric.elements.share.copied.to.clipboard.message':
    'Prepojenie sa skopírovalo do schránky',
  'fabric.elements.share.form.capabilities.info.message':
    'Vaše pozvanie sa odošle správcovi na schválenie',
  'fabric.elements.share.failure.message': 'Zdieľanie nie je možné',
};
