/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Slovak
export default {
  'fabric.elements.share.form.title': 'Zdieľanie',
  'fabric.elements.share.form.send': 'Odoslať',
  'fabric.elements.share.form.retry': 'Opakovať',
  'fabric.elements.share.form.comment.placeholder': 'Pridať správu',
  'fabric.elements.share.form.user-picker.placeholder.generic':
    'Zadajte meno, tím alebo e-mail',
  'fabric.elements.share.form.user-picker.placeholder.existingUserOnly':
    'Zadajte meno alebo tím',
  'fabric.elements.share.form.user-picker.add-more': 'Zadajte ďalšie položky',
  'fabric.elements.share.form.user-picker.validation.required':
    'Vyberte aspoň jedného používateľa, tím alebo e-mail.',
  'fabric.elements.share.form.user-picker.no-options.domainBasedUserOnly':
    'Môžete pozvať iba ľudí s e-mailovými adresami {domains}. Ak chcete pozvať iných ľudí, obráťte sa na svojho správcu stránky.',
  'fabric.elements.share.form.user-picker.no-options.existingUserOnly':
    'Nepodarilo sa nájsť žiadne výsledky pre „{inputValue}“.',
  'fabric.elements.share.form.user-picker.no-options.generic':
    'Nepodarilo sa nájsť žiadne výsledky pre „{inputValue}“. Pozvite ľudí pomocou e-mailovej adresy.',
  'fabric.elements.share.trigger.button.icon.label': 'Ikona zdieľania',
  'fabric.elements.share.trigger.button.text': 'Zdieľať',
  'fabric.elements.share.trigger.button.tooltip.text': 'Zdieľanie',
  'fabric.elements.share.trigger.button.invite.text': 'Pozvať',
  'fabric.elements.share.copylink.button.icon.label':
    'Kopírovať ikonu prepojenia',
  'fabric.elements.share.copylink.button.text': 'Kopírovať prepojenie',
  'fabric.elements.share.copied.to.clipboard.icon.label':
    'Kopírovať ikonu úspešného prepojenia',
  'fabric.elements.share.copied.to.clipboard.message':
    'Prepojenie sa skopírovalo do schránky',
  'fabric.elements.share.form.capabilities.info.message':
    'Vaše pozvanie sa odošle správcovi na schválenie',
  'fabric.elements.share.failure.icon.label': 'Ikona chyby',
  'fabric.elements.share.failure.message': 'Zdieľanie nie je možné',
  'fabric.elements.share.success.message':
    '{object, select, blogpost {Blog post shared} nástenka {Board shared} kalendár {Calendar shared} koncept {Draft shared} filter {Filter shared} problém {Issue shared} médiá {Media shared} stránka{Page shared} projekt {Project shared} žiadosť o vytiahnutie {Pull Request shared} otázka {Question shared} hlásenie {Report shared} schránka {Repository shared} požiadavka{Request shared} harmonogram{Roadmap shared} stránka{Site shared} priestor{Space shared} iné {Link Shared}}',
  'fabric.elements.share.admin.notified.message': 'Upozornil sa váš správca',
};
