/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Swedish
export default {
  'fabric.elements.share.form.title': 'Dela',
  'fabric.elements.share.form.send': 'Skicka',
  'fabric.elements.share.form.retry': 'Försök igen',
  'fabric.elements.share.form.comment.placeholder': 'Lägg till ett meddelande',
  'fabric.elements.share.form.user-picker.placeholder.generic':
    'Ange namn, team eller e-post',
  'fabric.elements.share.form.user-picker.placeholder.existingUserOnly':
    'Ange namn eller team',
  'fabric.elements.share.form.user-picker.add-more': 'Ange fler',
  'fabric.elements.share.form.user-picker.validation.required':
    'Välj minst en användare, team eller e-post',
  'fabric.elements.share.form.user-picker.no-options.domainBasedUserOnly':
    'Du kan bara bjuda in personer med e-postadresser med {domains}. Kontakta din administratör för att bjuda in andra personer.',
  'fabric.elements.share.form.user-picker.no-options.existingUserOnly':
    'Vi hittade inte några resultat för "{inputValue}".',
  'fabric.elements.share.form.user-picker.no-options.generic':
    'Vi hittade inte några resultat för "{inputValue}". Bjud in personer genom att använda e-postadresser.',
  'fabric.elements.share.trigger.button.icon.label': 'Dela-ikon',
  'fabric.elements.share.trigger.button.text': 'Dela',
  'fabric.elements.share.trigger.button.tooltip.text': 'Dela',
  'fabric.elements.share.trigger.button.invite.text': 'Bjud In',
  'fabric.elements.share.copylink.button.icon.label': 'Kopiera länk-ikon',
  'fabric.elements.share.copylink.button.text': 'Kopiera länk',
  'fabric.elements.share.copied.to.clipboard.icon.label':
    'Kopiera länk lyckades-ikon',
  'fabric.elements.share.copied.to.clipboard.message':
    'Länk kopierad till urklipp',
  'fabric.elements.share.form.capabilities.info.message':
    'Din inbjudan kommer att skickas till en administratör för godkännande',
  'fabric.elements.share.failure.icon.label': 'Fel-ikon',
  'fabric.elements.share.failure.message': 'Det gick inte att dela',
  'fabric.elements.share.success.message':
    '{object, select, blogpost {Blog post shared} anslagstavla {Board shared} kalender {Calendar shared} utkast {Draft shared} filter {Filter shared} ärende {Issue shared} media {Media shared} sida {Page shared} projekt {Project shared} pull-begäran{Pull Request shared} fråga {Question shared} rapport {Report shared} lagringsplats {Repository shared} förfrågan {Request shared} roadmap {Roadmap shared} webbplats {Site shared} utrymme {Space shared} annat {Link Shared}}',
  'fabric.elements.share.admin.notified.message':
    'Din administratör har meddelats',
};
