/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Swedish
export default {
  'fabric.elements.share.form.title': 'Dela',
  'fabric.elements.share.form.send': 'Skicka',
  'fabric.elements.share.form.retry': 'Försök igen',
  'fabric.elements.share.form.comment.placeholder': 'Lägg till ett meddelande',
  'fabric.elements.share.form.user-picker.placeholder':
    'Ange namn, team eller e-post',
  'fabric.elements.share.form.user-picker.add-more': 'Ange fler',
  'fabric.elements.share.form.user-picker.validation.required':
    'Välj minst en användare, team eller e-post',
  'fabric.elements.share.form.user-picker.no-options.emptyQuery':
    'Vi hittade inte några sökresultat. Bjud in personer med deras e-postadress.',
  'fabric.elements.share.form.user-picker.no-options':
    'Vi hittade inte några sökresultat för "{inputValue}". Bjud in personer med deras e-postadress.',
  'fabric.elements.share.trigger.button.text': 'Dela',
  'fabric.elements.share.copylink.button.text': 'Kopiera länk',
  'fabric.elements.share.copied.to.clipboard.message':
    'Länk kopierad till urklipp',
  'fabric.elements.share.form.capabilities.info.message':
    'Din inbjudan kommer att skickas till en administratör för godkännande',
  'fabric.elements.share.failure.message': 'Det gick inte att dela',
};
