/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Chinese
export default {
  'fabric.elements.share.form.title': '共享',
  'fabric.elements.share.form.send': '发送',
  'fabric.elements.share.form.retry': '重试',
  'fabric.elements.share.form.comment.placeholder': '添加消息',
  'fabric.elements.share.form.user-picker.placeholder': '输入姓名，团队或邮箱',
  'fabric.elements.share.form.user-picker.add-more': '输入更多',
  'fabric.elements.share.form.user-picker.validation.required':
    '至少选择一个用户，团队或邮箱。',
  'fabric.elements.share.form.user-picker.no-options.emptyQuery':
    '我们找不到任何结果，请用电子邮件地址邀请他人。',
  'fabric.elements.share.form.user-picker.no-options':
    '我们找不到任何关于“{inputValue}”的结果。请用电子邮件地址邀请他人。',
  'fabric.elements.share.trigger.button.text': '共享',
  'fabric.elements.share.copylink.button.text': '复制链接',
  'fabric.elements.share.copied.to.clipboard.message': '链接已复制到剪贴板',
  'fabric.elements.share.form.capabilities.info.message':
    '您的邀请将发送到管理员处进行审批',
  'fabric.elements.share.failure.message': '无法共享',
};
