/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Chinese
export default {
  'fabric.elements.share.form.title': '共享',
  'fabric.elements.share.form.send': '发送',
  'fabric.elements.share.form.retry': '重试',
  'fabric.elements.share.form.comment.placeholder': '添加消息',
  'fabric.elements.share.form.user-picker.placeholder.generic':
    '输入姓名、团队或电子邮箱',
  'fabric.elements.share.form.user-picker.placeholder.existingUserOnly':
    '输入名称或团队',
  'fabric.elements.share.form.user-picker.add-more': '输入更多',
  'fabric.elements.share.form.user-picker.validation.required':
    '至少选择一个用户，团队或邮箱。',
  'fabric.elements.share.form.user-picker.no-options.domainBasedUserOnly':
    '仅可邀请使用 {domains} 电子邮箱地址的人员。请联系站点管理员，以邀请其他人。',
  'fabric.elements.share.form.user-picker.no-options.existingUserOnly':
    '我们找不到任何关于“{inputValue}”的结果。',
  'fabric.elements.share.form.user-picker.no-options.generic':
    '我们找不到任何关于“{inputValue}”的结果。请用电子邮件地址邀请他人。',
  'fabric.elements.share.trigger.button.icon.label': '分享图标',
  'fabric.elements.share.trigger.button.text': '共享',
  'fabric.elements.share.trigger.button.tooltip.text': '分享',
  'fabric.elements.share.trigger.button.invite.text': '邀请',
  'fabric.elements.share.copylink.button.icon.label': '复制链接图标',
  'fabric.elements.share.copylink.button.text': '复制链接',
  'fabric.elements.share.copied.to.clipboard.icon.label': '复制链接成功图标',
  'fabric.elements.share.copied.to.clipboard.message': '链接已复制到剪贴板',
  'fabric.elements.share.form.capabilities.info.message':
    '您的邀请将发送到管理员处进行审批',
  'fabric.elements.share.failure.icon.label': '错误图标',
  'fabric.elements.share.failure.message': '无法共享',
  'fabric.elements.share.success.message':
    '{object, select, blogpost {Blog post shared} 面板 {Board shared} 日历 {Calendar shared} 草稿 {Draft shared} 筛选器 {Filter shared} 事务 {Issue shared} 媒体 {Media shared} 页面 {Page shared} 项目 {Project shared} pullrequest {Pull Request shared} 问题 {Question shared} 报告 {Report shared} 存储库 {Repository shared} 请求 {Request shared} 路线图 {Roadmap shared} 站点 {Site shared} 空间 {Space shared} 其他 {Link Shared}}',
  'fabric.elements.share.admin.notified.message': '管理员已接到通知',
};
