/**
 * NOTE:
 *
 * This file is automatically generated by the build process.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 *
 * To change the format of this file, modify icon/build/glyph-tsx.js.
 */
import React from "react";
import Icon, { Props } from "../src/components/Icon";

const ArrowUpCircleIcon = (props: Props) => (
  <Icon
    dangerouslySetGlyph={`<svg width="24" height="24" viewBox="0 0 24 24" focusable="false" role="presentation"><g fill-rule="evenodd"><circle fill="currentColor" fill-rule="nonzero" cx="12" cy="12" r="10"/><path d="M11.288 7.293L8.294 10.27a1.002 1.002 0 0 0 0 1.416 1.01 1.01 0 0 0 1.421 0l1.279-1.272V16c0 .552.451 1 1.006 1 .555 0 1.005-.448 1.005-1v-5.586l1.279 1.272a1.01 1.01 0 0 0 1.421 0 .998.998 0 0 0 0-1.416l-2.994-2.977a1.01 1.01 0 0 0-1.423 0z" fill="inherit"/></g></svg>`}
    {...props}  
  />
);
ArrowUpCircleIcon.displayName = "ArrowUpCircleIcon";
export default ArrowUpCircleIcon;

