/**
 * NOTE:
 *
 * This file is automatically generated by the build process.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 *
 * To change the format of this file, modify icon/build/glyph-tsx.js.
 */
import React from "react";
import Icon, { Props } from "../src/components/Icon";

const DocumentFilledIcon = (props: Props) => (
  <Icon
    dangerouslySetGlyph={`<svg width="24" height="24" viewBox="0 0 24 24" focusable="false" role="presentation"><path d="M18.99 8.99l.01 1.015V19a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5.275c.469 0 .922.164 1.282.464L18.631 7.7c.227.19.359.471.359.768v.521zM12.02 5L12 8.192a.99.99 0 0 0 .994.991h4L12.02 5z" fill="currentColor" fill-rule="evenodd"/></svg>`}
    {...props}  
  />
);
DocumentFilledIcon.displayName = "DocumentFilledIcon";
export default DocumentFilledIcon;

