/**
 * NOTE:
 *
 * This file is automatically generated by the build process.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 *
 * To change the format of this file, modify icon/build/glyph-tsx.js.
 */
import React from "react";
import Icon, { Props } from "../src/components/Icon";

const GoogledriveIcon = (props: Props) => (
  <Icon
    dangerouslySetGlyph={`<svg width="24" height="24" viewBox="0 0 24 24" focusable="false" role="presentation"><path d="M15.81 3l-6.776.068 5.846 10.126 6.777-.07L15.811 3zM2 14.315l3.447 5.835 5.846-10.126L7.846 4.19 2 14.315zm8.307.175l-3.33 5.902H18.67L22 14.49H10.307z" fill="currentColor" fill-rule="evenodd"/></svg>`}
    {...props}  
  />
);
GoogledriveIcon.displayName = "GoogledriveIcon";
export default GoogledriveIcon;

