/**
 * NOTE:
 *
 * This file is automatically generated by the build process.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 *
 * To change the format of this file, modify icon/build/glyph-tsx.js.
 */
import React from "react";
import Icon, { Props } from "../src/components/Icon";

const GraphBarIcon = (props: Props) => (
  <Icon
    dangerouslySetGlyph={`<svg width="24" height="24" viewBox="0 0 24 24" focusable="false" role="presentation"><g fill="currentColor" fill-rule="evenodd"><rect x="17" y="5" width="4" height="11" rx="2"/><rect x="11" y="8" width="4" height="8" rx="2"/><rect x="5" y="11" width="4" height="5" rx="2"/><path d="M21 17H4.995C4.448 17 4 16.548 4 15.991V6a1 1 0 1 0-2 0v9.991A3.004 3.004 0 0 0 4.995 19H21a1 1 0 0 0 0-2z" fill-rule="nonzero"/></g></svg>`}
    {...props}  
  />
);
GraphBarIcon.displayName = "GraphBarIcon";
export default GraphBarIcon;

