/**
 * NOTE:
 *
 * This file is automatically generated by the build process.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 *
 * To change the format of this file, modify icon/build/glyph-tsx.js.
 */
import React from "react";
import Icon, { Props } from "../src/components/Icon";

const ImageIcon = (props: Props) => (
  <Icon
    dangerouslySetGlyph={`<svg width="24" height="24" viewBox="0 0 24 24" focusable="false" role="presentation"><path d="M3 4.995C3 3.893 3.893 3 4.995 3h14.01C20.107 3 21 3.893 21 4.995v14.01A1.995 1.995 0 0 1 19.005 21H4.995A1.995 1.995 0 0 1 3 19.005V4.995zM10.5 16.5L9 15l-3 3h12v-2.7L15 12l-4.5 4.5zM8 10a2 2 0 1 0 0-4 2 2 0 0 0 0 4z" fill="currentColor" fill-rule="evenodd"/></svg>`}
    {...props}  
  />
);
ImageIcon.displayName = "ImageIcon";
export default ImageIcon;

