/**
 * NOTE:
 *
 * This file is automatically generated by the build process.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 *
 * To change the format of this file, modify icon/build/glyph-tsx.js.
 */
import React from "react";
import Icon, { Props } from "../src/components/Icon";

const ListIcon = (props: Props) => (
  <Icon
    dangerouslySetGlyph={`<svg width="24" height="24" viewBox="0 0 24 24" focusable="false" role="presentation"><path d="M3 18c0 .552.445 1 .993 1h16.014A.994.994 0 0 0 21 18v-1H3v1zm0-7h18V9H3zm0-4h18V6c0-.552-.445-1-.993-1H3.993A.994.994 0 0 0 3 6v1zm0 8h18v-2H3z" fill="currentColor"/></svg>`}
    {...props}  
  />
);
ListIcon.displayName = "ListIcon";
export default ListIcon;

