/**
 * NOTE:
 *
 * This file is automatically generated by the build process.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 *
 * To change the format of this file, modify icon/build/glyph-tsx.js.
 */
import React from "react";
import Icon, { Props } from "../src/components/Icon";

const PdfIcon = (props: Props) => (
  <Icon
    dangerouslySetGlyph={`<svg width="24" height="24" viewBox="0 0 24 24" focusable="false" role="presentation"><g fill-rule="evenodd"><rect fill="currentColor" x="5" y="4" width="14" height="16" rx="2"/><rect fill="inherit" x="8" y="8" width="8" height="2" rx="1"/><path d="M15.512 16H13.49a.492.492 0 0 1-.489-.497v-4.006c0-.275.218-.497.489-.497h2.023c.27 0 .488.222.488.497v4.006a.492.492 0 0 1-.488.497" fill="inherit"/><rect fill="inherit" x="8" y="11" width="4" height="2" rx="1"/><rect fill="inherit" x="8" y="14" width="4" height="2" rx="1"/></g></svg>`}
    {...props}  
  />
);
PdfIcon.displayName = "PdfIcon";
export default PdfIcon;

