/**
 * NOTE:
 *
 * This file is automatically generated by the build process.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 *
 * To change the format of this file, modify icon/build/glyph-tsx.js.
 */
import React from "react";
import Icon, { Props } from "../src/components/Icon";

const PreferencesIcon = (props: Props) => (
  <Icon
    dangerouslySetGlyph={`<svg width="24" height="24" viewBox="0 0 24 24" focusable="false" role="presentation"><g fill="currentColor" fill-rule="evenodd"><path d="M3 7h3v2H3zm0 8h11v2H3zm7-8h11v2H10zm8 8h3v2h-3z"/><path d="M11 8a3 3 0 1 1-5.999.001A3 3 0 0 1 11 8zM9 8a1 1 0 1 0-1.999-.001A1 1 0 0 0 9 8zm10 8a3 3 0 1 1-5.999.001A3 3 0 0 1 19 16zm-2 0a1 1 0 1 0-1.999-.001A1 1 0 0 0 17 16z"/></g></svg>`}
    {...props}  
  />
);
PreferencesIcon.displayName = "PreferencesIcon";
export default PreferencesIcon;

