/**
 * NOTE:
 *
 * This file is automatically generated by the build process.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 *
 * To change the format of this file, modify icon/build/glyph-tsx.js.
 */
import React from "react";
import Icon, { Props } from "../src/components/Icon";

const PresenceUnavailableIcon = (props: Props) => (
  <Icon
    dangerouslySetGlyph={`<svg width="24" height="24" viewBox="0 0 24 24" focusable="false" role="presentation"><path d="M6 12a6 6 0 1 1 12 0 6 6 0 0 1-12 0z" fill="inherit"/><path d="M15 12a3 3 0 1 0-6 0 3 3 0 0 0 6 0zm-9 0a6 6 0 1 1 12 0 6 6 0 0 1-12 0z" fill="currentColor"/></svg>`}
    {...props}  
  />
);
PresenceUnavailableIcon.displayName = "PresenceUnavailableIcon";
export default PresenceUnavailableIcon;

