/**
 * NOTE:
 *
 * This file is automatically generated by the build process.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 *
 * To change the format of this file, modify icon/build/glyph-tsx.js.
 */
import React from "react";
import Icon, { Props } from "../src/components/Icon";

const PresenceActiveIcon = (props: Props) => (
  <Icon
    dangerouslySetGlyph={`<svg width="24" height="24" viewBox="0 0 24 24" focusable="false" role="presentation"><circle cx="12" cy="12" r="6" fill="currentColor" fill-rule="evenodd"/></svg>`}
    {...props}  
  />
);
PresenceActiveIcon.displayName = "PresenceActiveIcon";
export default PresenceActiveIcon;

