/**
 * NOTE:
 *
 * This file is automatically generated by the build process.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 *
 * To change the format of this file, modify icon/build/glyph-tsx.js.
 */
import React from "react";
import Icon, { Props } from "../src/components/Icon";

const VidConnectionCircleIcon = (props: Props) => (
  <Icon
    dangerouslySetGlyph={`<svg width="24" height="24" viewBox="0 0 24 24" focusable="false" role="presentation"><g fill-rule="evenodd"><circle fill="currentColor" cx="12" cy="12" r="10"/><rect fill="inherit" x="14" y="8" width="2" height="8" rx="1"/><rect fill="inherit" x="11" y="10" width="2" height="6" rx="1"/><rect fill="inherit" x="8" y="13" width="2" height="3" rx="1"/></g></svg>`}
    {...props}  
  />
);
VidConnectionCircleIcon.displayName = "VidConnectionCircleIcon";
export default VidConnectionCircleIcon;

