/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Czech
export default {
  'fabric.mention.noAccess.warning':
    'Uživatel {name} nebude informován, protože nemá přístup',
  'fabric.mention.noAccess.label': 'Žádný přístup',
  'fabric.mention.error.defaultHeadline': 'Něco se pokazilo',
  'fabric.mention.error.defaultAction': 'Zkuste to znovu za pár sekund',
  'fabric.mention.error.loginAgain': 'Zkuste se odhlásit a znovu přihlásit',
  'fabric.mention.error.differentText': 'Zkuste zadat jiný text',
  'fabric.elements.mentions.team.member.count':
    '{0, plural, one{{count} member{includes, select, true {, including you} other {}}} few{{count} members{includes, select, true {, including you} other {}}} many{{count} members{includes, select, true {, including you} other {}}} other{{count} members{includes, select, true {, including you} other {}}}}',
  'fabric.elements.mentions.team.member.50plus':
    '50+ members{includes, select, true {, including you} other {}}',
};
