/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Czech
export default {
  'fabric.mention.noAccess.warning':
    'Uživatel {name} nebude informován, protože nemá přístup',
  'fabric.mention.noAccess.label': 'Žádný přístup',
  'fabric.mention.error.defaultHeadline': 'Něco se pokazilo',
  'fabric.mention.error.defaultAction': 'Zkuste to znovu za pár sekund',
  'fabric.mention.error.loginAgain': 'Zkuste se odhlásit a znovu přihlásit',
  'fabric.mention.error.differentText': 'Zkuste zadat jiný text',
  'fabric.elements.mentions.team.member.count':
    '{0, plural, one{1 member} few{{0} members} many{{0} members} other{{0} members}}',
  'fabric.elements.mentions.team.member.count.including.you':
    '{0, plural, one{1 member, including you} few{{0} members, including you} many{{0} members, including you} other{{0} members, including you}}',
  'fabric.elements.mentions.team.member.50plus': '50+ members',
  'fabric.elements.mentions.team.member.50plus.including.you':
    '50+ members, including you',
};
