/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Danish
export default {
  'fabric.mention.noAccess.warning':
    '{name} får ikke besked, da personen ikke har adgang',
  'fabric.mention.noAccess.label': 'Ingen adgang',
  'fabric.mention.error.defaultHeadline': 'Noget gik galt',
  'fabric.mention.error.defaultAction': 'Prøv igen om nogle sekunder',
  'fabric.mention.error.loginAgain': 'Prøv at logge ud og derefter ind igen',
  'fabric.mention.error.differentText': 'Prøv at indtaste en anden tekst',
  'fabric.elements.mentions.team.member.count':
    '{0, plural, one{1 medlem} other{{0} medlemmer}}',
  'fabric.elements.mentions.team.member.count.including.you':
    '{0, plural, one{1 member, including you} other{{0} members, including you}}',
  'fabric.elements.mentions.team.member.50plus': '50+ medlemmer',
  'fabric.elements.mentions.team.member.50plus.including.you':
    '50+ medlemmer, inklusive dig',
};
