/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Danish
export default {
  'fabric.mention.noAccess.warning':
    '{name} får ikke besked, da personen ikke har adgang',
  'fabric.mention.noAccess.label': 'Ingen adgang',
  'fabric.mention.error.defaultHeadline': 'Noget gik galt',
  'fabric.mention.error.defaultAction': 'Prøv igen om nogle sekunder',
  'fabric.mention.error.loginAgain': 'Prøv at logge ud og derefter ind igen',
  'fabric.mention.error.differentText': 'Prøv at indtaste en anden tekst',
  'fabric.elements.mentions.team.member.count':
    '{0, plural, one{{count} medlem{includes, select, true {, including you} andre {}}} other{{count} medlemmer{includes, select, true {, including you} andre {}}}}',
  'fabric.elements.mentions.team.member.50plus':
    '50+ medlemmer{includes, select, true {, including you} andre {}} ',
};
