/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// German
export default {
  'fabric.mention.noAccess.warning':
    '{name} wird nicht benachrichtigt, da diese Person keinen Zugriff besitzt.',
  'fabric.mention.noAccess.label': 'Kein Zugriff',
  'fabric.mention.error.defaultHeadline': 'Irgendetwas ist schiefgelaufen',
  'fabric.mention.error.defaultAction':
    'Versuchen Sie es in ein paar Sekunden erneut.',
  'fabric.mention.error.loginAgain': 'Melden Sie sich ab und wieder an.',
  'fabric.mention.error.differentText':
    'Versuchen Sie, einen anderen Text einzugeben.',
  'fabric.elements.mentions.team.member.count':
    '{0, plural, one{{count} Mitglied{einschließlich, select, true {, einschließlich Ihnen} other {}}} other{{count} Mitglieder{einschließlich, select, true {, einschließlich Ihnen} other {}}}}',
  'fabric.elements.mentions.team.member.50plus':
    '50+ Mitglieder{einschließlich, select, true {, einschließlich Ihnen} other {}}',
};
