/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// English
export default {
  'fabric.mention.noAccess.warning':
    "{name} won't be notified as they have no access",
  'fabric.mention.noAccess.label': 'No access',
  'fabric.mention.error.defaultHeadline': 'Something went wrong',
  'fabric.mention.error.defaultAction': 'Try again in a few seconds',
  'fabric.mention.error.loginAgain': 'Try logging out then in again',
  'fabric.mention.error.differentText': 'Try entering different text',
  'fabric.elements.mentions.team.member.count':
    '{0, plural, one{{count} member{includes, select, true {, including you} other {}}} other{{count} members{includes, select, true {, including you} other {}}}}',
  'fabric.elements.mentions.team.member.50plus':
    '50+ members{includes, select, true {, including you} other {}}',
};
