/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Spanish
export default {
  'fabric.mention.noAccess.warning':
    '{name} no recibirá una notificación porque no tiene acceso',
  'fabric.mention.noAccess.label': 'Sin acceso',
  'fabric.mention.error.defaultHeadline': 'Algo ha ido mal',
  'fabric.mention.error.defaultAction': 'Vuelve a intentarlo en unos segundos',
  'fabric.mention.error.loginAgain': 'Prueba a cerrar y abrir sesión de nuevo',
  'fabric.mention.error.differentText': 'Prueba a escribir otro texto',
  'fabric.elements.mentions.team.member.count':
    '{0, plural, one{1 member} other{{0} members}}',
  'fabric.elements.mentions.team.member.count.including.you':
    '{0, plural, one{1 member, including you} other{{0} members, including you}}',
  'fabric.elements.mentions.team.member.50plus': '50+ members',
  'fabric.elements.mentions.team.member.50plus.including.you':
    '50+ members, including you',
};
