/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Estonian
export default {
  'fabric.mention.noAccess.warning':
    'Kasutajat {name} ei teavitata, kuna tal puudub juurdepääs',
  'fabric.mention.noAccess.label': 'Juurdepääs puudub',
  'fabric.mention.error.defaultHeadline': 'Midagi läks nässu',
  'fabric.mention.error.defaultAction': 'Proovi paari sekundi pärast uuesti',
  'fabric.mention.error.loginAgain': 'Proovi logida välja ja taas sisse',
  'fabric.mention.error.differentText': 'Proovi sisestada muud teksti',
  'fabric.elements.mentions.team.member.count':
    '{0, plural, one{{count} member{includes, select, true {, including you} other {}}} other{{count} members{includes, select, true {, including you} other {}}}}',
  'fabric.elements.mentions.team.member.50plus':
    '50+ members{includes, select, true {, including you} other {}}',
};
