/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// French
export default {
  'fabric.mention.noAccess.warning':
    "{name} ne sera pas prévenu, car cet utilisateur n'a pas d'accès",
  'fabric.mention.noAccess.label': 'Aucun accès',
  'fabric.mention.error.defaultHeadline': "Une erreur s'est produite",
  'fabric.mention.error.defaultAction': 'Réessayez dans quelques secondes',
  'fabric.mention.error.loginAgain':
    'Essayez de vous déconnecter et de vous reconnecter',
  'fabric.mention.error.differentText': 'Essayer de modifier le texte',
  'fabric.elements.mentions.team.member.count':
    '{0, plural, one{1 member} other{{0} members}}',
  'fabric.elements.mentions.team.member.count.including.you':
    '{0, plural, one{1 member, including you} other{{0} members, including you}}',
  'fabric.elements.mentions.team.member.50plus': '50+ members',
  'fabric.elements.mentions.team.member.50plus.including.you':
    '50+ members, including you',
};
