/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Hungarian
export default {
  'fabric.mention.noAccess.warning':
    '{name} nem kap értesítést, mert nincs hozzáférése.',
  'fabric.mention.noAccess.label': 'Nincs hozzáférés',
  'fabric.mention.error.defaultHeadline': 'Hiba történt.',
  'fabric.mention.error.defaultAction':
    'Néhány másodperc múlva próbálja meg újból.',
  'fabric.mention.error.loginAgain':
    'Próbáljon meg kijelentkezni, majd újból bejelentkezni.',
  'fabric.mention.error.differentText': 'Próbáljon meg más szöveget beírni.',
  'fabric.elements.mentions.team.member.count':
    '{0, plural, one{{count} member{includes, select, true {, including you} other {}}} other{{count} members{includes, select, true {, including you} other {}}}}',
  'fabric.elements.mentions.team.member.50plus':
    '50+ members{includes, select, true {, including you} other {}}',
};
