/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Hungarian
export default {
  'fabric.mention.noAccess.warning':
    '{name} nem kap értesítést, mert nincs hozzáférése.',
  'fabric.mention.noAccess.label': 'Nincs hozzáférés',
  'fabric.mention.error.defaultHeadline': 'Hiba történt.',
  'fabric.mention.error.defaultAction':
    'Néhány másodperc múlva próbálja meg újból.',
  'fabric.mention.error.loginAgain':
    'Próbáljon meg kijelentkezni, majd újból bejelentkezni.',
  'fabric.mention.error.differentText': 'Próbáljon meg más szöveget beírni.',
  'fabric.elements.mentions.team.member.count':
    '{0, plural, one{1 member} other{{0} members}}',
  'fabric.elements.mentions.team.member.count.including.you':
    '{0, plural, one{1 member, including you} other{{0} members, including you}}',
  'fabric.elements.mentions.team.member.50plus': '50+ members',
  'fabric.elements.mentions.team.member.50plus.including.you':
    '50+ members, including you',
};
