/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Icelandic
export default {
  'fabric.mention.noAccess.warning':
    '{name} mun ekki fá tilkynningu þar sem þeir hafa ekki aðgang',
  'fabric.mention.noAccess.label': 'Enginn aðgangur',
  'fabric.mention.error.defaultHeadline': 'Eitthvað fór úrskeiðis',
  'fabric.mention.error.defaultAction': 'Reyndu aftur eftir nokkrar sekúndur',
  'fabric.mention.error.loginAgain': 'Reyndu að skrá þig út og svo inn aftur',
  'fabric.mention.error.differentText': 'Reyndu að slá inn annan texta',
  'fabric.elements.mentions.team.member.count':
    '{0, plural, one{{count} member{includes, select, true {, including you} other {}}} other{{count} members{includes, select, true {, including you} other {}}}}',
  'fabric.elements.mentions.team.member.50plus':
    '50+ members{includes, select, true {, including you} other {}}',
};
