/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Japanese
export default {
  'fabric.mention.noAccess.warning':
    '{name} さんはアクセス権限がないため、通知されません',
  'fabric.mention.noAccess.label': 'アクセス権限がありません',
  'fabric.mention.error.defaultHeadline': '問題が発生しました',
  'fabric.mention.error.defaultAction': '数秒後にもう一度お試しください',
  'fabric.mention.error.loginAgain':
    '一度ログアウトしてからもう一度ログインしてみてください',
  'fabric.mention.error.differentText': '別のテキストを入力してください',
  'fabric.elements.mentions.team.member.count': '{0, plural, other{1 member}}',
  'fabric.elements.mentions.team.member.count.including.you':
    '{0, plural, other{1 member, including you}}',
  'fabric.elements.mentions.team.member.50plus': '50+ members',
  'fabric.elements.mentions.team.member.50plus.including.you':
    '50+ members, including you',
};
