/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Korean
export default {
  'fabric.mention.noAccess.warning':
    '{name}은(는) 액세스 권한이 없어 알림을 받지 못합니다.',
  'fabric.mention.noAccess.label': '액세스 권한 없음',
  'fabric.mention.error.defaultHeadline': '문제가 발생했습니다.',
  'fabric.mention.error.defaultAction': '몇 초 후에 다시 시도하십시오.',
  'fabric.mention.error.loginAgain': '로그아웃한 다음 다시 로그인해 보십시오.',
  'fabric.mention.error.differentText': '다른 텍스트를 입력해 보십시오.',
  'fabric.elements.mentions.team.member.count': '{0, plural, other{1 member}}',
  'fabric.elements.mentions.team.member.count.including.you':
    '{0, plural, other{1 member, including you}}',
  'fabric.elements.mentions.team.member.50plus': '50+ members',
  'fabric.elements.mentions.team.member.50plus.including.you':
    '50+ members, including you',
};
