/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Norwegian Bokmål
export default {
  'fabric.mention.noAccess.warning':
    '{name} blir ikke varslet, da de ikke har tilgang',
  'fabric.mention.noAccess.label': 'Ingen tilgang',
  'fabric.mention.error.defaultHeadline': 'Det oppsto en feil',
  'fabric.mention.error.defaultAction': 'Prøv igjen om noen øyeblikk',
  'fabric.mention.error.loginAgain': 'Prøv å logge av og deretter på igjen',
  'fabric.mention.error.differentText': 'Prøv med å skrive inn annen tekst',
  'fabric.elements.mentions.team.member.count':
    '{0, plural, one{1 member} other{{0} members}}',
  'fabric.elements.mentions.team.member.count.including.you':
    '{0, plural, one{1 member, including you} other{{0} members, including you}}',
  'fabric.elements.mentions.team.member.50plus': '50+ members',
  'fabric.elements.mentions.team.member.50plus.including.you':
    '50+ members, including you',
};
