/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Norwegian Bokmål
export default {
  'fabric.mention.noAccess.warning':
    '{name} blir ikke varslet, da de ikke har tilgang',
  'fabric.mention.noAccess.label': 'Ingen tilgang',
  'fabric.mention.error.defaultHeadline': 'Det oppsto en feil',
  'fabric.mention.error.defaultAction': 'Prøv igjen om noen øyeblikk',
  'fabric.mention.error.loginAgain': 'Prøv å logge av og deretter på igjen',
  'fabric.mention.error.differentText': 'Prøv med å skrive inn annen tekst',
  'fabric.elements.mentions.team.member.count':
    '{0, plural, one{{count} member{includes, select, true {, including you} other {}}} other{{count} members{includes, select, true {, including you} other {}}}}',
  'fabric.elements.mentions.team.member.50plus':
    '50+ members{includes, select, true {, including you} other {}}',
};
