/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Dutch
export default {
  'fabric.mention.noAccess.warning':
    '{name} ontvangt geen melding omdat hij/zij geen toegang heeft',
  'fabric.mention.noAccess.label': 'Geen toegang',
  'fabric.mention.error.defaultHeadline': 'Er is iets misgegaan',
  'fabric.mention.error.defaultAction':
    'Probeer het over een paar seconden opnieuw',
  'fabric.mention.error.loginAgain':
    'Log uit en probeer dan opnieuw in te loggen',
  'fabric.mention.error.differentText':
    'Probeer het opnieuw met een andere tekst',
  'fabric.elements.mentions.team.member.count':
    '{0, plural, one{{count} member{includes, select, true {, including you} other {}}} other{{count} members{includes, select, true {, including you} other {}}}}',
  'fabric.elements.mentions.team.member.50plus':
    '50+ members{includes, select, true {, including you} other {}}',
};
