/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Dutch
export default {
  'fabric.mention.noAccess.warning':
    '{name} ontvangt geen melding omdat hij/zij geen toegang heeft',
  'fabric.mention.noAccess.label': 'Geen toegang',
  'fabric.mention.error.defaultHeadline': 'Er is iets misgegaan',
  'fabric.mention.error.defaultAction':
    'Probeer het over een paar seconden opnieuw',
  'fabric.mention.error.loginAgain':
    'Log uit en probeer dan opnieuw in te loggen',
  'fabric.mention.error.differentText':
    'Probeer het opnieuw met een andere tekst',
  'fabric.elements.mentions.team.member.count':
    '{0, plural, one{1 member} other{{0} members}}',
  'fabric.elements.mentions.team.member.count.including.you':
    '{0, plural, one{1 member, including you} other{{0} members, including you}}',
  'fabric.elements.mentions.team.member.50plus': '50+ members',
  'fabric.elements.mentions.team.member.50plus.including.you':
    '50+ members, including you',
};
