/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Polish
export default {
  'fabric.mention.noAccess.warning':
    'Użytkownicy: {name} nie zostaną powiadomieni, ponieważ nie mają dostępu',
  'fabric.mention.noAccess.label': 'Brak dostępu',
  'fabric.mention.error.defaultHeadline': 'Coś poszło nie tak',
  'fabric.mention.error.defaultAction': 'Spróbuj ponownie za chwilę',
  'fabric.mention.error.loginAgain':
    'Spróbuj się wylogować i zalogować ponownie',
  'fabric.mention.error.differentText': 'Spróbuj wpisać inny tekst',
  'fabric.elements.mentions.team.member.count':
    '{0, plural, one{1 użytkownik} few{{0} użytkowników} many{{0} użytkowników} other{{0} użytkownika}}',
  'fabric.elements.mentions.team.member.count.including.you':
    '{0, plural, one{1 member, including you} few{{0} members, including you} many{{0} members, including you} other{{0} members, including you}}',
  'fabric.elements.mentions.team.member.50plus': '50+ użytkowników',
  'fabric.elements.mentions.team.member.50plus.including.you':
    '50+ użytkowników wliczając Ciebie',
};
