/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Polish
export default {
  'fabric.mention.noAccess.warning':
    'Użytkownicy: {name} nie zostaną powiadomieni, ponieważ nie mają dostępu',
  'fabric.mention.noAccess.label': 'Brak dostępu',
  'fabric.mention.error.defaultHeadline': 'Coś poszło nie tak',
  'fabric.mention.error.defaultAction': 'Spróbuj ponownie za chwilę',
  'fabric.mention.error.loginAgain':
    'Spróbuj się wylogować i zalogować ponownie',
  'fabric.mention.error.differentText': 'Spróbuj wpisać inny tekst',
  'fabric.elements.mentions.team.member.count':
    '{0, plural, one{{count} członek {includes, select, true {, including you} other {}}} few{{count} członków {includes, select, true {, including you} other {}}} many{{count} członków {includes, select, true {, including you} other {}}} other{{count} członka {includes, select, true {, including you} other {}}}}',
  'fabric.elements.mentions.team.member.50plus':
    'Ponad 50 członków{includes, select, true {, łącznie z Tobą} other {}}',
};
