/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Portuguese (Brazil)
export default {
  'fabric.mention.noAccess.warning':
    '{name} não será notificado(a) porque não tem acesso',
  'fabric.mention.noAccess.label': 'Sem acesso',
  'fabric.mention.error.defaultHeadline': 'Algo deu errado',
  'fabric.mention.error.defaultAction': 'Tente novamente em alguns segundos',
  'fabric.mention.error.loginAgain': 'Tente sair e fazer login novamente',
  'fabric.mention.error.differentText': 'Tente inserir outro texto',
  'fabric.elements.mentions.team.member.count':
    '{0, plural, one{1 membro} other{{0} membros}}',
  'fabric.elements.mentions.team.member.count.including.you':
    '{0, plural, one{{0} użytkownika wliczając Ciebie} other{{0} użytkownika wliczając Ciebie}}',
  'fabric.elements.mentions.team.member.50plus': '50+ membros',
  'fabric.elements.mentions.team.member.50plus.including.you':
    '50+ membros, incluindo você',
};
