/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Portuguese (Portugal)
export default {
  'fabric.mention.noAccess.warning':
    '{name} não será notificado, uma vez que não tem acesso',
  'fabric.mention.noAccess.label': 'Sem acesso',
  'fabric.mention.error.defaultHeadline': 'Ocorreu um erro',
  'fabric.mention.error.defaultAction':
    'Tente novamente dentro de alguns segundos',
  'fabric.mention.error.loginAgain':
    'Tente terminar sessão e, em seguida, iniciar sessão novamente',
  'fabric.mention.error.differentText': 'Tente introduzir um texto diferente',
  'fabric.elements.mentions.team.member.count':
    '{0, plural, one{1 member} other{{0} members}}',
  'fabric.elements.mentions.team.member.count.including.you':
    '{0, plural, one{1 member, including you} other{{0} members, including you}}',
  'fabric.elements.mentions.team.member.50plus': '50+ members',
  'fabric.elements.mentions.team.member.50plus.including.you':
    '50+ members, including you',
};
