/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Portuguese (Portugal)
export default {
  'fabric.mention.unknow.user.error': 'Utilizador desconhecido {id}',
  'fabric.mention.noAccess.warning':
    '{name} não será notificado, uma vez que não tem acesso',
  'fabric.mention.noAccess.label': 'Sem acesso',
  'fabric.mention.error.defaultHeadline': 'Ocorreu um erro',
  'fabric.mention.error.defaultAction':
    'Tente novamente dentro de alguns segundos',
  'fabric.mention.error.loginAgain':
    'Tente terminar sessão e, em seguida, iniciar sessão novamente',
  'fabric.mention.error.differentText': 'Tente introduzir um texto diferente',
  'fabric.elements.mentions.team.member.count':
    '{0, plural, one{1 membro} other{{0} membros}}',
  'fabric.elements.mentions.team.member.count.including.you':
    '{0, plural, one{{0} membros, incluindo o utilizador} other{{0} membros, incluindo o utilizador}}',
  'fabric.elements.mentions.team.member.50plus': 'Mais de 50 membros',
  'fabric.elements.mentions.team.member.50plus.including.you':
    'Mais de 50 membros, incluindo o utilizador',
};
