/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Romanian
export default {
  'fabric.mention.noAccess.warning':
    '{name} nu va fi notificat deoarece nu are acces',
  'fabric.mention.noAccess.label': 'Fără acces',
  'fabric.mention.error.defaultHeadline': 'Ceva nu a funcționat corect',
  'fabric.mention.error.defaultAction': 'Încercați din nou după câteva secunde',
  'fabric.mention.error.loginAgain': 'Deconectați-vă și conectați-vă din nou',
  'fabric.mention.error.differentText': 'Introduceți un text diferit',
  'fabric.elements.mentions.team.member.count':
    '{0, plural, one{{count} member{includes, select, true {, including you} other {}}} few{{count} members{includes, select, true {, including you} other {}}} other{{count} members{includes, select, true {, including you} other {}}}}',
  'fabric.elements.mentions.team.member.50plus':
    '50+ members{includes, select, true {, including you} other {}}',
};
