/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Russian
export default {
  'fabric.mention.noAccess.warning':
    '{name} не получит уведомление, так как доступ для этого пользователя закрыт.',
  'fabric.mention.noAccess.label': 'Нет доступа',
  'fabric.mention.error.defaultHeadline': 'Произошла ошибка',
  'fabric.mention.error.defaultAction':
    'Повторите попытку через несколько секунд.',
  'fabric.mention.error.loginAgain':
    'Выйдите из системы, а затем войдите снова.',
  'fabric.mention.error.differentText': 'Попробуйте ввести другой текст.',
  'fabric.elements.mentions.team.member.count':
    '{0, plural, one{1 участник} few{{0} участника} many{{0} участников} other{{0} участника}}',
  'fabric.elements.mentions.team.member.count.including.you':
    '{0, plural, one{1 member, including you} few{{0} members, including you} many{{0} members, including you} other{{0} members, including you}}',
  'fabric.elements.mentions.team.member.50plus': 'Более 50 участников',
  'fabric.elements.mentions.team.member.50plus.including.you':
    'Более 50 участников, включая вас',
};
