/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Russian
export default {
  'fabric.mention.noAccess.warning':
    '{name} не получит уведомление, так как доступ для этого пользователя закрыт.',
  'fabric.mention.noAccess.label': 'Нет доступа',
  'fabric.mention.error.defaultHeadline': 'Произошла ошибка',
  'fabric.mention.error.defaultAction':
    'Повторите попытку через несколько секунд.',
  'fabric.mention.error.loginAgain':
    'Выйдите из системы, а затем войдите снова.',
  'fabric.mention.error.differentText': 'Попробуйте ввести другой текст.',
  'fabric.elements.mentions.team.member.count':
    '{0, plural, one{{count} member{includes, select, true {, including you} other {}}} few{{count} members{includes, select, true {, including you} other {}}} many{{count} members{includes, select, true {, including you} other {}}} other{{count} members{includes, select, true {, including you} other {}}}}',
  'fabric.elements.mentions.team.member.50plus':
    '50+ members{includes, select, true {, including you} other {}}',
};
