/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Slovak
export default {
  'fabric.mention.noAccess.warning':
    'Používateľ {name} sa neupozorní. pretože nemá prístup',
  'fabric.mention.noAccess.label': 'Žiadny prístup',
  'fabric.mention.error.defaultHeadline': 'Vyskytol sa problém',
  'fabric.mention.error.defaultAction': 'Skúste to znova o chvíľu',
  'fabric.mention.error.loginAgain': 'Skúste sa odhlásiť a následne prihlásiť',
  'fabric.mention.error.differentText': 'Skúste zadať iný text',
  'fabric.elements.mentions.team.member.count':
    '{0, plural, one{{count} člen{includes, select, true {, including you} other {}}} few{{count} členovia{includes, select, true {, including you} other {}}} many{{count} členov{includes, select, true {, including you} other {}}} other{{count} členov{includes, select, true {, including you} other {}}}}',
  'fabric.elements.mentions.team.member.50plus':
    'Viac ako 50 členov{includes, select, true {, including you} other {}}',
};
