/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Swedish
export default {
  'fabric.mention.noAccess.warning':
    '{name} kommer inte att meddelas eftersom de saknar åtkomst',
  'fabric.mention.noAccess.label': 'Ingen åtkomst',
  'fabric.mention.error.defaultHeadline': 'Något gick fel',
  'fabric.mention.error.defaultAction': 'Försök igen om några sekunder',
  'fabric.mention.error.loginAgain':
    'Prova att logga ut och sedan logga in igen',
  'fabric.mention.error.differentText': 'Prova att skriva en annan text',
  'fabric.elements.mentions.team.member.count':
    '{0, plural, one{{count} medlem{includes, select, true {, including you} other {}}} other{{count} medlemmar{includes, select, true {, including you} other {}}}}',
  'fabric.elements.mentions.team.member.50plus':
    '50+ medlemmar{includes, select, true {, including you} other {}}',
};
