/**
 * NOTE:
 *
 * This file is automatically generated by the build process.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 *
 * To change the format of this file, modify icon/build/glyph-tsx.js.
 */
import React from "react";
import Icon, { Props } from "../../src/components/Icon";

const HipchatChevronUpIcon = (props: Props) => (
  <Icon
    dangerouslySetGlyph={`<svg width="24" height="24" viewBox="0 0 24 24" focusable="false" role="presentation"><path d="M11.294 8.708l-.001.001-4.549 4.559a1.051 1.051 0 1 0 1.486 1.488l.001-.001 3.77-3.776 3.768 3.776a1.05 1.05 0 0 0 1.486.001h.001a1.054 1.054 0 0 0 .001-1.489l-4.548-4.558a1 1 0 0 0-1.415-.001z" fill="currentColor" fill-rule="evenodd"/></svg>`}
    {...props}  
  />
);
HipchatChevronUpIcon.displayName = "HipchatChevronUpIcon";
export default HipchatChevronUpIcon;

