/**
 * NOTE:
 *
 * This file is automatically generated by the build process.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 *
 * To change the format of this file, modify icon/build/glyph-tsx.js.
 */
import React from "react";
import Icon, { Props } from "../../src/components/Icon";

const HipchatLobbyIcon = (props: Props) => (
  <Icon
    dangerouslySetGlyph={`<svg width="24" height="24" viewBox="0 0 24 24" focusable="false" role="presentation"><g fill="currentColor" fill-rule="evenodd"><path d="M5 14a7.002 7.002 0 0 1 13.858 0H5z"/><rect x="4" y="15" width="16" height="2" rx="1"/><path d="M11 7h2v3h-2z"/><rect x="10" y="6" width="4" height="1" rx=".5"/></g></svg>`}
    {...props}  
  />
);
HipchatLobbyIcon.displayName = "HipchatLobbyIcon";
export default HipchatLobbyIcon;

