/**
 * NOTE:
 *
 * This file is automatically generated by the build process.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 *
 * To change the format of this file, modify icon/build/glyph-tsx.js.
 */
import React from "react";
import Icon, { Props } from "../../src/components/Icon";

const MediaServicesBlurIcon = (props: Props) => (
  <Icon
    dangerouslySetGlyph={`<svg width="24" height="24" viewBox="0 0 24 24" focusable="false" role="presentation"><g fill="currentColor"><path d="M4.889 4H12v8H4V4.889C4 4.398 4.398 4 4.889 4z"/><path d="M4 12h8v8H4.889A.889.889 0 0 1 4 19.111V12z" opacity=".4"/><path d="M12 4h7.111c.491 0 .889.398.889.889V12h-8V4z" opacity=".55"/><path d="M12 12h8v7.111a.889.889 0 0 1-.889.889H12v-8z" opacity=".75"/></g></svg>`}
    {...props}  
  />
);
MediaServicesBlurIcon.displayName = "MediaServicesBlurIcon";
export default MediaServicesBlurIcon;

