/**
 * NOTE:
 *
 * This file is automatically generated by the build process.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 *
 * To change the format of this file, modify icon/build/glyph-tsx.js.
 */
import React from "react";
import Icon, { Props } from "../../src/components/Icon";

const MediaServicesImageIcon = (props: Props) => (
  <Icon
    dangerouslySetGlyph={`<svg width="24" height="24" viewBox="0 0 24 24" focusable="false" role="presentation"><g fill-rule="evenodd"><rect fill="currentColor" x="4" y="4" width="16" height="16" rx="2"/><circle fill="inherit" cx="8.667" cy="8.667" r="2"/><path fill="inherit" d="M6.667 17.333l2.666-2.666L12 17.333z"/><path fill="inherit" d="M14.667 12l2.666 2.933v2.4h-8z"/></g></svg>`}
    {...props}  
  />
);
MediaServicesImageIcon.displayName = "MediaServicesImageIcon";
export default MediaServicesImageIcon;

