/**
 * NOTE:
 *
 * This file is automatically generated by the build process.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 *
 * To change the format of this file, modify icon/build/glyph-tsx.js.
 */
import React from "react";
import Icon, { Props } from "../../src/components/Icon";

const MediaServicesPdfIcon = (props: Props) => (
  <Icon
    dangerouslySetGlyph={`<svg width="24" height="24" viewBox="0 0 24 24" focusable="false" role="presentation"><g fill-rule="evenodd"><rect fill="currentColor" x="4" y="4" width="16" height="16" rx="2"/><rect fill="inherit" x="7" y="8" width="10" height="2" rx="1"/><path d="M16.187 16h-3.373c-.45 0-.814-.222-.814-.497v-4.006c0-.275.364-.497.814-.497h3.373c.45 0 .813.222.813.497v4.006c0 .275-.364.497-.813.497" fill="inherit"/><rect fill="inherit" x="7" y="11" width="4" height="2" rx="1"/><rect fill="inherit" x="7" y="14" width="4" height="2" rx="1"/></g></svg>`}
    {...props}  
  />
);
MediaServicesPdfIcon.displayName = "MediaServicesPdfIcon";
export default MediaServicesPdfIcon;

