/**
 * NOTE:
 *
 * This file is automatically generated by the build process.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 *
 * To change the format of this file, modify icon/build/glyph-tsx.js.
 */
import React from "react";
import Icon, { Props } from "../../src/components/Icon";

const MediaServicesPresentationIcon = (props: Props) => (
  <Icon
    dangerouslySetGlyph={`<svg width="24" height="24" viewBox="0 0 24 24" focusable="false" role="presentation"><g fill-rule="evenodd"><rect fill="currentColor" x="4" y="4" width="16" height="16" rx="2"/><rect fill="inherit" x="8" y="12" width="2" height="3" rx="1"/><rect fill="inherit" x="11" y="10" width="2" height="5" rx="1"/><rect fill="inherit" x="14" y="8" width="2" height="7" rx="1"/></g></svg>`}
    {...props}  
  />
);
MediaServicesPresentationIcon.displayName = "MediaServicesPresentationIcon";
export default MediaServicesPresentationIcon;

