/**
 * NOTE:
 *
 * This file is automatically generated by the build process.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 *
 * To change the format of this file, modify icon/build/glyph-tsx.js.
 */
import React from "react";
import Icon, { Props } from "../../src/components/Icon";

const MediaServicesSpreadsheetIcon = (props: Props) => (
  <Icon
    dangerouslySetGlyph={`<svg width="24" height="24" viewBox="0 0 24 24" focusable="false" role="presentation"><g fill-rule="evenodd"><rect fill="currentColor" x="4" y="4" width="16" height="16" rx="2"/><rect fill="inherit" x="7" y="8" width="4" height="2" rx="1"/><rect fill="inherit" x="7" y="11" width="4" height="2" rx="1"/><rect fill="inherit" x="13" y="11" width="4" height="2" rx="1"/><rect fill="inherit" x="7" y="14" width="4" height="2" rx="1"/><rect fill="inherit" x="13" y="14" width="4" height="2" rx="1"/><rect fill="inherit" x="13" y="8" width="4" height="2" rx="1"/></g></svg>`}
    {...props}  
  />
);
MediaServicesSpreadsheetIcon.displayName = "MediaServicesSpreadsheetIcon";
export default MediaServicesSpreadsheetIcon;

