/**
 * NOTE:
 *
 * This file is automatically generated by the build process.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 *
 * To change the format of this file, modify icon/build/glyph-tsx.js.
 */
import React from "react";
import Icon, { Props } from "../../src/components/Icon";

const MediaServicesZipIcon = (props: Props) => (
  <Icon
    dangerouslySetGlyph={`<svg width="24" height="24" viewBox="0 0 24 24" focusable="false" role="presentation"><g fill-rule="evenodd"><rect fill="currentColor" x="4" y="4" width="16" height="16" rx="2"/><path d="M9 6.999C9 6.447 9.443 6 9.999 6H12v3H9.999A.996.996 0 0 1 9 8.001V6.999zM12 9h2.001c.552 0 .999.443.999.999v1.002a.996.996 0 0 1-.999.999H12V9zm-3 3.999c0-.552.443-.999.999-.999H12v3H9.999A.996.996 0 0 1 9 14.001v-1.002zM12 15h2.001c.552 0 .999.443.999.999v1.002a.996.996 0 0 1-.999.999H12v-3z" fill="inherit"/></g></svg>`}
    {...props}  
  />
);
MediaServicesZipIcon.displayName = "MediaServicesZipIcon";
export default MediaServicesZipIcon;

