/**
 * NOTE:
 *
 * This file is automatically generated by the build process.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 *
 * To change the format of this file, modify icon/build/glyph-tsx.js.
 */
import React from "react";
import Icon, { Props } from "../../src/components/Icon";

const MediaServicesZoomOutIcon = (props: Props) => (
  <Icon
    dangerouslySetGlyph={`<svg width="24" height="24" viewBox="0 0 24 24" focusable="false" role="presentation"><path d="M16.436 15.085l3.94 4.01a1 1 0 0 1-1.425 1.402l-3.938-4.006a7.5 7.5 0 1 1 1.423-1.406zM13.5 11.5h-6a1 1 0 0 1 0-2h6a1 1 0 0 1 0 2" fill="currentColor" fill-rule="evenodd"/></svg>`}
    {...props}  
  />
);
MediaServicesZoomOutIcon.displayName = "MediaServicesZoomOutIcon";
export default MediaServicesZoomOutIcon;

