/**
 * NOTE:
 *
 * This file is automatically generated by the build process.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 *
 * To change the format of this file, modify icon/build/createIconsDocs.js.
 * Add synonyms in icon/icons/synonyms.js.
 */
declare const _default: {
    activity: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'add-circle': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'add-item': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    add: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    addon: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'app-access': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'app-switcher': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'arrow-down-circle': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'arrow-down': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'arrow-left-circle': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'arrow-left': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'arrow-right-circle': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'arrow-right': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'arrow-up-circle': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'arrow-up': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    attachment: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'audio-circle': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    audio: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    backlog: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'billing-filled': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    billing: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'bitbucket/branches': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'bitbucket/builds': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'bitbucket/clone': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'bitbucket/commits': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'bitbucket/compare': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'bitbucket/forks': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'bitbucket/output': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'bitbucket/pipelines': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'bitbucket/pullrequests': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'bitbucket/repos': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'bitbucket/snippets': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'bitbucket/source': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    board: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    book: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'bullet-list': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'calendar-filled': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    calendar: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'camera-filled': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'camera-rotate': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'camera-take-picture': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    camera: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    canvas: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'check-circle-outline': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'check-circle': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    check: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'checkbox-indeterminate': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    checkbox: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'chevron-down-circle': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'chevron-down': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'chevron-left-circle': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'chevron-left-large': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'chevron-left': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'chevron-right-circle': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'chevron-right-large': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'chevron-right': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'chevron-up-circle': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'chevron-up': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'child-issues': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    code: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    comment: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    component: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    copy: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'creditcard-filled': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    creditcard: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'cross-circle': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    cross: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    dashboard: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    decision: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    department: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'detail-view': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'discover-filled': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    discover: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'document-filled': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    document: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    documents: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    download: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'drag-handler': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    dropbox: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'edit-filled': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    edit: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/add': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/addon': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/advanced': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/align-center': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/align-image-center': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/align-image-left': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/align-image-right': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/align-left': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/align-right': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/attachment': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/background-color': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/bold': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/bullet-list': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/close': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/code': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/collapse': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/date': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/decision': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/divider': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/done': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/edit': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/emoji': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/error': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/expand': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/feedback': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/file': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/help': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/hint': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/horizontal-rule': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/image-border': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/image-resize': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/image': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/indent': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/info': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/italic': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/layout-three-equal': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/layout-three-with-sidebars': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/layout-two-equal': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/layout-two-left-sidebar': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/layout-two-right-sidebar': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/link': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/media-center': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/media-full-width': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/media-wide': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/media-wrap-left': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/media-wrap-right': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/mention': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/more': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/note': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/number-list': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/open': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/outdent': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/panel': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/photo': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/quote': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/recent': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/redo': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/remove': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/search': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/settings': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/strikethrough': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/success': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/table-display-options': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/table': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/task': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/text-color': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/text-style': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/underline': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/undo': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/unlink': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'editor/warning': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    email: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'emoji-add': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    emoji: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'emoji/activity': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'emoji/atlassian': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'emoji/custom': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'emoji/emoji': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'emoji/flags': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'emoji/food': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'emoji/frequent': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'emoji/keyboard': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'emoji/nature': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'emoji/objects': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'emoji/people': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'emoji/productivity': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'emoji/symbols': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'emoji/travel': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    error: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    export: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    feedback: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    file: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    filter: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'flag-filled': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'folder-filled': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    folder: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    followers: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    following: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    googledrive: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'graph-bar': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'graph-line': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    gsuite: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    highlights: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'hipchat/audio-only': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'hipchat/chevron-double-down': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'hipchat/chevron-double-up': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'hipchat/chevron-down': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'hipchat/chevron-up': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'hipchat/dial-out': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'hipchat/lobby': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'hipchat/media-attachment-count': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'hipchat/outgoing-sound': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'hipchat/sd-video': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'home-circle': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    home: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'image-border': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'image-resize': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    image: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    info: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'invite-team': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'issue-raise': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    issue: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    issues: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'jira/capture': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'jira/failed-build-status': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'jira/labs': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'jira/test-session': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    label: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'lightbulb-filled': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    lightbulb: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    like: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'link-filled': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    link: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    list: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    location: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'lock-circle': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'lock-filled': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    lock: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    marketplace: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'media-services/actual-size': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'media-services/add-comment': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'media-services/annotate': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'media-services/arrow': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'media-services/audio': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'media-services/blur': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'media-services/brush': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'media-services/button-option': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'media-services/code': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'media-services/document': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'media-services/filter': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'media-services/fit-to-page': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'media-services/full-screen': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'media-services/grid': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'media-services/image': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'media-services/line-thickness': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'media-services/line': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'media-services/no-image': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'media-services/open-mediaviewer': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'media-services/oval': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'media-services/pdf': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'media-services/preselected': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'media-services/presentation': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'media-services/rectangle': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'media-services/scale-large': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'media-services/scale-small': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'media-services/spreadsheet': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'media-services/text': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'media-services/unknown': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'media-services/video': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'media-services/zip': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'media-services/zoom-in': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'media-services/zoom-out': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    mention: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'menu-expand': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    menu: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'more-vertical': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    more: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'notification-all': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'notification-direct': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    notification: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'office-building-filled': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'office-building': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    open: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    overview: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'page-filled': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    page: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    pdf: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'people-group': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    people: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'person-circle': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    person: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    portfolio: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    preferences: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    premium: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'presence-active': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'presence-busy': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'presence-unavailable': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'question-circle': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    question: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    questions: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    queues: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    quote: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    radio: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    recent: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    redo: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    refresh: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    retry: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    roadmap: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'room-menu': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'schedule-filled': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    schedule: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    screen: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    search: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'select-clear': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    send: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    settings: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    share: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    ship: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    shortcut: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'sign-in': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'sign-out': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'star-filled': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'star-large': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    star: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    status: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    subtask: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    suitcase: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    switcher: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    table: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    task: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    trash: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    tray: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    undo: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    unlink: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'unlock-circle': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'unlock-filled': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    unlock: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    upload: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'user-avatar-circle': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'vid-audio-muted': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'vid-audio-on': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'vid-backward': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'vid-camera-off': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'vid-camera-on': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'vid-connection-circle': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'vid-forward': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'vid-full-screen-off': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'vid-full-screen-on': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'vid-hang-up': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'vid-hd-circle': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'vid-pause': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'vid-play': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'vid-raised-hand': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'vid-share-screen': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'vid-speaking-circle': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'vid-volume-full': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'vid-volume-half': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'vid-volume-muted': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'video-circle': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'video-filled': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    warning: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'watch-filled': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    watch: {
        keywords: string[];
        componentName: string;
        package: string;
    };
    'world-small': {
        keywords: string[];
        componentName: string;
        package: string;
    };
    world: {
        keywords: string[];
        componentName: string;
        package: string;
    };
};
export default _default;
