/**
 * NOTE:
 *
 * This file is automatically generated by the build process.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 *
 * To change the format of this file, modify icon/build/glyph-tsx.js.
 */
import React from "react";
import Icon, { Props } from "../../src/components/Icon";

const EditorAdvancedIcon = (props: Props) => (
  <Icon
    dangerouslySetGlyph={`<svg width="24" height="24" viewBox="0 0 24 24" focusable="false" role="presentation"><path d="M9.8 17L9 19H7l.763-2H9.8zm-.893-3l1.907-5h2.372l1.907 5h-1.926L12 10.5 10.833 14H8.907zm7.33 3L17 19h-2l-.8-2h2.037zM5 15h14v1H5v-1zM18 5v1h-2v2h2v1h-3V5h3zm0 1h1v2h-1V6z" fill="currentColor" fill-rule="evenodd"/></svg>`}
    {...props}  
  />
);
EditorAdvancedIcon.displayName = "EditorAdvancedIcon";
export default EditorAdvancedIcon;

