/**
 * NOTE:
 *
 * This file is automatically generated by the build process.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 *
 * To change the format of this file, modify icon/build/glyph-tsx.js.
 */
import React from "react";
import Icon, { Props } from "../../src/components/Icon";

const EditorAlignImageRightIcon = (props: Props) => (
  <Icon
    dangerouslySetGlyph={`<svg width="24" height="24" focusable="false" role="presentation"><path d="M6 17h12a1 1 0 0 1 0 2H6a1 1 0 0 1 0-2zm8-8h4a1 1 0 0 1 1 1v4a1 1 0 0 1-1 1h-4a1 1 0 0 1-1-1v-4a1 1 0 0 1 1-1zM6 5h12a1 1 0 0 1 0 2H6a1 1 0 1 1 0-2z" fill="currentColor" fill-rule="evenodd"/></svg>`}
    {...props}  
  />
);
EditorAlignImageRightIcon.displayName = "EditorAlignImageRightIcon";
export default EditorAlignImageRightIcon;

