/**
 * NOTE:
 *
 * This file is automatically generated by the build process.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 *
 * To change the format of this file, modify icon/build/glyph-tsx.js.
 */
import React from "react";
import Icon, { Props } from "../../src/components/Icon";

const EditorImageResizeIcon = (props: Props) => (
  <Icon
    dangerouslySetGlyph={`<svg width="24" height="24" viewBox="0 0 24 24" focusable="false" role="presentation"><path d="M15 9.707V11h1V8h-3v1h1.293L9 14.293V13H8v3h3v-1H9.707L15 9.707zM6 6.5c0-.276.229-.5.5-.5h11c.276 0 .5.229.5.5v11c0 .276-.229.5-.5.5h-11a.504.504 0 0 1-.5-.5v-11z" fill="currentColor" fill-rule="evenodd"/></svg>`}
    {...props}  
  />
);
EditorImageResizeIcon.displayName = "EditorImageResizeIcon";
export default EditorImageResizeIcon;

