/**
 * NOTE:
 *
 * This file is automatically generated by the build process.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 *
 * To change the format of this file, modify icon/build/glyph-tsx.js.
 */
import React from "react";
import Icon, { Props } from "../../src/components/Icon";

const EditorMediaFullWidthIcon = (props: Props) => (
  <Icon
    dangerouslySetGlyph={`<svg width="24" height="24" viewBox="0 0 24 24" focusable="false" role="presentation"><path d="M7 17h10a1 1 0 0 1 0 2H7a1 1 0 0 1 0-2zM4 5h16a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V6a1 1 0 0 1 1-1z" fill="currentColor" fill-rule="evenodd"/></svg>`}
    {...props}  
  />
);
EditorMediaFullWidthIcon.displayName = "EditorMediaFullWidthIcon";
export default EditorMediaFullWidthIcon;

