// DO NOT EDIT THIS FILE DIRECTLY!
// This file was auto generated and may be overritten.
// To make changes, use the generator.

export * from './info';
export * from './note';
export * from './tip';
export * from './success';
export * from './warning';
export * from './error';
export * from './decision';
export * from './taskItemChecked';
export * from './taskItemUnchecked';
export * from './genericAttachment';
export * from './audioAttachment';
export * from './videoAttachment';
export * from './archiveAttachment';
export * from './documentAttachment';

export enum IconName {
  info = 'info',
  note = 'note',
  tip = 'tip',
  success = 'success',
  warning = 'warning',
  error = 'error',
  decision = 'decision',
  taskItemChecked = 'taskItemChecked',
  taskItemUnchecked = 'taskItemUnchecked',
  genericAttachment = 'genericAttachment',
  audioAttachment = 'audioAttachment',
  videoAttachment = 'videoAttachment',
  archiveAttachment = 'archiveAttachment',
  documentAttachment = 'documentAttachment',
}

export type IconString =
  | 'info'
  | 'note'
  | 'tip'
  | 'success'
  | 'warning'
  | 'error'
  | 'decision'
  | 'taskItemChecked'
  | 'taskItemUnchecked'
  | 'genericAttachment'
  | 'audioAttachment'
  | 'videoAttachment'
  | 'archiveAttachment'
  | 'documentAttachment';
